apiVersion: v1
kind: Pod
metadata:
   name: hello-cisco2
   labels:
      env: test
spec:
   containers:
   - name: hello-cisco
     image: mimaurer/hello-cisco:v1
     ports:
     - containerPort: 5000