---
- name: Step 1
  hosts: kube
  become: yes

  roles:
    - docker

- name: Step 2
  hosts: kube
  become: yes

  tasks:
    - name: Add Kubernetes Repo to yum
      yum_repository:
        name: kubernetes
        description: Kubernetes
        baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-\$basearch
        gpgcheck: no
        repo_gpgcheck: no
        gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg


    - name: Install Kubernetes tools
      with_items:
        - kubernetes-cni-0.5.1-1
        - kubelet-1.15
        - kubelet-1.7.15-0
        - kubeadm-1.15
        #- kubeadm-1.7.15-0
        - kubectl-1.15
        #- kubectl-1.7.15-0
      yum:
        name: "{{ item }}"
        state: present

    - name: IP Tables Fix
      with_items:
        - net.bridge.bridge-nf-call-ip6tables = 1
        - net.bridge.bridge-nf-call-iptables = 1
        - net.ipv4.ip_forward = 1
      lineinfile:
        path: /etc/sysctl.d/k8s.conf
        line: "{{ item }}"
        create: yes
        owner: root
        group: root
        mode: 0644

    - name: Start kubelet
      service:
        name: kubelet
        state: started
        enabled: yes

    # - name: Fix cgroup driver
    #   command: sed -i "s/cgroup-driver=systemd/cgroup-driver=cgroupfs/g" /etc/systemd/system/kubelet.service.d/10-kubeadm.conf

    - name: Fix cgroup driver
      replace:
        path: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
        regexp: cgroup-driver=systemd
        replace: cgroup-driver=cgroupfs
        backup: no

    - name: Reload systemctl daemon
      command: systemctl daemon-reload

    - name: Restart kubelet
      service:
        name: kubelet
        state: restarted
        enabled: yes

    # Disabling port open because firewalld is just disabled anyway
    # - name: Open ports for Kubernetes
    #   with_items:
    #     - 6443
    #     - 10250
    #   firewalld:
    #     port: "{{ item }}/tcp"
    #     immediate: yes
    #     permanent: true
    #     state: enabled

    - name: Disable firewalld
      service:
        name: firewalld
        state: stopped
        enabled: no
