apiVersion: v1
kind: ConfigMap
metadata:
  name: aci-containers-config
  namespace: kube-system
  labels:
    aci-containers-config-version: "32a9cc63-1809-43f3-86de-6becd68d053e"
    network-plugin: aci-containers
data:
  controller-config: |-
    {
        "log-level": "info",
        "apic-hosts": [
            "10.10.20.12"
        ],
        "apic-username": "kubesbx46",
        "apic-private-key-path": "/usr/local/etc/aci-cert/user.key",
        "aci-prefix": "kubesbx46",
        "aci-vmm-type": "Kubernetes",
        "aci-vmm-domain": "kubesbx46",
        "aci-vmm-controller": "kubesbx46",
        "aci-policy-tenant": "kubesbx46",
        "require-netpol-annot": false,
        "aci-service-phys-dom": "kubesbx46-pdom",
        "aci-service-encap": "vlan-995",
        "aci-service-monitor-interval": 15,
        "aci-vrf-tenant": "common",
        "aci-l3out": "sbx_shared_L3Out",
        "aci-ext-networks": [
            "any_ip"
        ],
        "aci-vrf": "sbx_shared",
        "default-endpoint-group": {
            "policy-space": "kubesbx46",
            "name": "kubernetes|kube-default"
        },
        "namespace-default-endpoint-group": {
            "kube-system": {
                "policy-space": "kubesbx46",
                "name": "kubernetes|kube-system"
            }
        },
        "service-ip-pool": [
            {
                "start": "172.20.46.194", 
                "end": "172.20.46.222"
            }
        ],
        "static-service-ip-pool": [
            {
                "start": "172.20.46.226", 
                "end": "172.20.46.254"
            }
        ],
        "pod-ip-pool": [
            {
                "start": "10.246.0.2", 
                "end": "10.246.255.254"
            }
        ],
        "node-service-ip-pool": [
            {
                "start": "192.168.146.2", 
                "end": "192.168.146.254"
            }
        ],
        "node-service-subnets": [
            "192.168.146.1/24"
        ]
    }
  host-agent-config: |-
    {
        "log-level": "info",
        "aci-vmm-type": "Kubernetes",
        "aci-vmm-domain": "kubesbx46",
        "aci-vmm-controller": "kubesbx46",
        "aci-vrf": "sbx_shared",
        "aci-vrf-tenant": "common",
        "service-vlan": 995,
        "encap-type": "vxlan",
        "aci-infra-vlan": 4093,
        "cni-netconfig": [
            {
                "routes": [
                    {
                        "gw": "10.246.0.1", 
                        "dst": "0.0.0.0/0"
                    }
                ], 
                "subnet": "10.246.0.0/16", 
                "gateway": "10.246.0.1"
            }
        ]
    }
  opflex-agent-config: |-
    {
        "log": {
            "level": "info"
        },
        "opflex": {
        }
    }
---
apiVersion: v1
kind: Secret
metadata:
  name: aci-user-cert
  namespace: kube-system
  labels:
    aci-containers-config-version: "32a9cc63-1809-43f3-86de-6becd68d053e"
data:
  user.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUNlQUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQW1Jd2dnSmVBZ0VBQW9HQkFMVnFaRVFIS1plbUJZU0oKNGdZUjRNLzRQUmhrcDRwS2pMNjd4MFFkUWlUcWM4SDJySENQL1BsSXNwaFVmaDMzUFl0dTRtT0hxblFrMFRWaQpMLys5cXloeURmUXlqb2JidjdYRHNYSGc4Q1Jnb1hYR3NRRVAxdzkzNDJ0UERFY0gxTDZncTFGK3lnM1pxSzIzCkVGdG5kNGNmMXd0N01VTzhNZHEwTUFhVFBQbGpBZ01CQUFFQ2dZRUFweEY5bVBDSHF6S25yakZVeDRZN1pRc1YKS0p1NWR5L0VnZnBvUGlBN3c4ZHVKMWhGNGJ1WW12SUtGeUxvcWl3QXI2SEVOeWkvSHdxdzU5cXVuWFJNWS9yMgpjM3V2OE44N3hYNlU1cmJFOHk4VkJyR0drNGdZcUdNLzlXUmRCU3R2SnpNK0NIRDloRDNtSHFPVU43ZW1ZTVF5CmF1NXBTeVNMR0sySVVYeGdTVEVDUVFEbjR4QUxGTlJzM3NVcnhadVlPNUp6SXNDektmc1NvOXJibERDY3Q1SFgKeGZQQnkrNHZuaHlxRlJORFlPM2JoQXQ1ejF6aVlGZHprdUdWT1ZLeENjR0hBa0VBeUVmQ0NLcWllc1QrS0I1TwpuTDMrd25WWHZhbXFKVzFNQmx1Ry9tN0REQ2U0M2cyUVUyRXBPR3hRb2JRVWFkUzRpZ05nVDBnMVUwOFV0TGIvClZMbXdSUUpCQUxJK1QyNjFMRFFqYU53a29WMTdMUzlqWDB4WTBLMmJWZmZEQ1RydHdDVmorK0xUcHRyalpwVTIKYmdBMDJhRUs5dWREQmRyY3cxd0xZMnNaRFA4WXlMRUNRQjBUSGIzNFY0SVBHdjVqOS9HVk8yaXJkRU5hWUJMeQozUGlIVFArZXdMNEEvanR1S0tlU0VWUFpsWk1EKzNxcG9PaVlPT0VKa0lRNWxMM3ZXdjNIdnlrQ1FRQ0NKZlRJClluMU9MNFQ5aE9jVFFQMDhtWnFSZkk3Wk5neUZIa3hDRVpmNHhUL1NKRU1nYUlNYjdQOUZjQzE1cWJOUEIvdUMKT1NVSGNnNGxWUTkvdk5JVAotLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tCg==
  user.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUI3RENDQVZVQ0FnUG9NQTBHQ1NxR1NJYjNEUUVCQlFVQU1ENHhDekFKQmdOVkJBWVRBbFZUTVJZd0ZBWUQKVlFRS0RBMURhWE5qYnlCVGVYTjBaVzF6TVJjd0ZRWURWUVFEREE1VmMyVnlJR3QxWW1WelluZzBOakFlRncweApPREE0TURrd05UVTJNVGxhRncweU9EQTRNRFl4TnpVMk1UbGFNRDR4Q3pBSkJnTlZCQVlUQWxWVE1SWXdGQVlEClZRUUtEQTFEYVhOamJ5QlRlWE4wWlcxek1SY3dGUVlEVlFRRERBNVZjMlZ5SUd0MVltVnpZbmcwTmpDQm56QU4KQmdrcWhraUc5dzBCQVFFRkFBT0JqUUF3Z1lrQ2dZRUF0V3BrUkFjcGw2WUZoSW5pQmhIZ3ovZzlHR1NuaWtxTQp2cnZIUkIxQ0pPcHp3ZmFzY0kvOCtVaXltRlIrSGZjOWkyN2lZNGVxZENUUk5XSXYvNzJyS0hJTjlES09odHUvCnRjT3hjZUR3SkdDaGRjYXhBUS9YRDNmamEwOE1Sd2ZVdnFDclVYN0tEZG1vcmJjUVcyZDNoeC9YQzNzeFE3d3gKMnJRd0JwTTgrV01DQXdFQUFUQU5CZ2txaGtpRzl3MEJBUVVGQUFPQmdRQWhodi94eDIzSGduUUFRaTFuQ1R2UApIeDg5RDZTT2JGYlNQVDJBcXZSKy9kRGNtRzF1UlJFcUttQTdReFE4dml5YWsrSitxNWk3a1BTY1NrMXlDV3J3CjRWS1V6eUtOV2JwaWNXL2xDc0Rmd0ZMNTIrUFRRclNFUTRuTDI0NFovTUtiSEZ3MVF4OG9kUXBlbmJzMG1odXMKRHBWTWxhRUN1TjUzNFJlUDVQZ2lGQT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aci-containers-controller
  namespace: kube-system
  labels:
    aci-containers-config-version: "32a9cc63-1809-43f3-86de-6becd68d053e"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aci-containers-host-agent
  namespace: kube-system
  labels:
    aci-containers-config-version: "32a9cc63-1809-43f3-86de-6becd68d053e"
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:
    aci-containers-config-version: "32a9cc63-1809-43f3-86de-6becd68d053e"
    network-plugin: aci-containers
  name: aci-containers:controller
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - namespaces
  - pods
  - endpoints
  - services
  verbs:
  - list
  - watch
  - get
- apiGroups:
  - "networking.k8s.io"
  resources:
  - networkpolicies
  verbs:
  - list
  - watch
  - get
- apiGroups:
  - "extensions"
  resources:
  - deployments
  - replicasets
  verbs:
  - list
  - watch
  - get
- apiGroups:
  - ""
  resources:
  - pods
  - nodes
  - services/status
  verbs:
  - update
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:
    aci-containers-config-version: "32a9cc63-1809-43f3-86de-6becd68d053e"
    network-plugin: aci-containers
  name: aci-containers:host-agent
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - pods
  - endpoints
  - services
  verbs:
  - list
  - watch
  - get
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: aci-containers:controller
  labels:
    aci-containers-config-version: "32a9cc63-1809-43f3-86de-6becd68d053e"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: aci-containers:controller
subjects:
- kind: ServiceAccount
  name: aci-containers-controller
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: aci-containers:host-agent
  labels:
    aci-containers-config-version: "32a9cc63-1809-43f3-86de-6becd68d053e"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: aci-containers:host-agent
subjects:
- kind: ServiceAccount
  name: aci-containers-host-agent
  namespace: kube-system
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: aci-containers-host
  namespace: kube-system
  labels:
    aci-containers-config-version: "32a9cc63-1809-43f3-86de-6becd68d053e"
    network-plugin: aci-containers
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      name: aci-containers-host
      network-plugin: aci-containers
  template:
    metadata:
      labels:
        name: aci-containers-host
        network-plugin: aci-containers
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      hostNetwork: true
      hostPID: true
      hostIPC: true
      serviceAccountName: aci-containers-host-agent
      tolerations:
        - key: CriticalAddonsOnly
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
      containers:
        - name: aci-containers-host
          image: noiro/aci-containers-host:1.7r86
          imagePullPolicy: Always
          securityContext:
            capabilities:
              add:
                - SYS_ADMIN
                - NET_ADMIN
          env:
            - name: KUBERNETES_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: cni-bin
              mountPath: /mnt/cni-bin
            - name: cni-conf
              mountPath: /mnt/cni-conf
            - name: hostvar
              mountPath: /usr/local/var
            - name: hostrun
              mountPath: /run
            - name: hostrun
              mountPath: /usr/local/run
            - name: opflex-hostconfig-volume
              mountPath: /usr/local/etc/opflex-agent-ovs/base-conf.d
            - name: host-config-volume
              mountPath: /usr/local/etc/aci-containers/
          livenessProbe:
            httpGet:
              path: /status
              port: 8090
        - name: opflex-agent
          image: noiro/opflex:1.7r70
          imagePullPolicy: Always
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          volumeMounts:
            - name: hostvar
              mountPath: /usr/local/var
            - name: hostrun
              mountPath: /run
            - name: hostrun
              mountPath: /usr/local/run
            - name: opflex-hostconfig-volume
              mountPath: /usr/local/etc/opflex-agent-ovs/base-conf.d
            - name: opflex-config-volume
              mountPath: /usr/local/etc/opflex-agent-ovs/conf.d
        - name: mcast-daemon
          image: noiro/opflex:1.7r70
          command: ["/bin/sh"]
          args: ["/usr/local/bin/launch-mcastdaemon.sh"]
          imagePullPolicy: Always
          volumeMounts:
            - name: hostvar
              mountPath: /usr/local/var
            - name: hostrun
              mountPath: /run
            - name: hostrun
              mountPath: /usr/local/run
      restartPolicy: Always
      volumes:
        - name: cni-bin
          hostPath:
            path: /opt
        - name: cni-conf
          hostPath:
            path: /etc
        - name: hostvar
          hostPath:
            path: /var
        - name: hostrun
          hostPath:
            path: /run
        - name: host-config-volume
          configMap:
            name: aci-containers-config
            items:
              - key: host-agent-config
                path: host-agent.conf
        - name: opflex-hostconfig-volume
          emptyDir:
            medium: Memory
        - name: opflex-config-volume
          configMap:
            name: aci-containers-config
            items:
              - key: opflex-agent-config
                path: local.conf
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: aci-containers-openvswitch
  namespace: kube-system
  labels:
    aci-containers-config-version: "32a9cc63-1809-43f3-86de-6becd68d053e"
    network-plugin: aci-containers
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      name: aci-containers-openvswitch
      network-plugin: aci-containers
  template:
    metadata:
      labels:
        name: aci-containers-openvswitch
        network-plugin: aci-containers
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      hostNetwork: true
      hostPID: true
      hostIPC: true
      serviceAccountName: aci-containers-host-agent
      tolerations:
        - key: CriticalAddonsOnly
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
      containers:
        - name: aci-containers-openvswitch
          image: noiro/openvswitch:1.7r24
          imagePullPolicy: Always
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - SYS_MODULE
                - SYS_NICE
                - IPC_LOCK
          env:
            - name: OVS_RUNDIR
              value: /usr/local/var/run/openvswitch
          volumeMounts:
            - name: hostvar
              mountPath: /usr/local/var
            - name: hostrun
              mountPath: /run
            - name: hostrun
              mountPath: /usr/local/run
            - name: hostetc
              mountPath: /usr/local/etc
            - name: hostmodules
              mountPath: /lib/modules
          livenessProbe:
            exec:
              command:
                - /usr/local/bin/liveness-ovs.sh
      restartPolicy: Always
      volumes:
        - name: hostetc
          hostPath:
            path: /etc
        - name: hostvar
          hostPath:
            path: /var
        - name: hostrun
          hostPath:
            path: /run
        - name: hostmodules
          hostPath:
            path: /lib/modules
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: aci-containers-controller
  namespace: kube-system
  labels:
    aci-containers-config-version: "32a9cc63-1809-43f3-86de-6becd68d053e"
    network-plugin: aci-containers
    name: aci-containers-controller
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      name: aci-containers-controller
      network-plugin: aci-containers
  template:
    metadata:
      name: aci-containers-controller
      namespace: kube-system
      labels:
        name: aci-containers-controller
        network-plugin: aci-containers
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      hostNetwork: true
      serviceAccountName: aci-containers-controller
      tolerations:
        - key: CriticalAddonsOnly
      containers:
        - name: aci-containers-controller
          image: noiro/aci-containers-controller:1.7r86
          imagePullPolicy: Always
          volumeMounts:
            - name: controller-config-volume
              mountPath: /usr/local/etc/aci-containers/
            - name: aci-user-cert-volume
              mountPath: /usr/local/etc/aci-cert/
          livenessProbe:
            httpGet:
              path: /status
              port: 8091
      volumes:
        - name: aci-user-cert-volume
          secret:
            secretName: aci-user-cert
        - name: controller-config-volume
          configMap:
            name: aci-containers-config
            items:
              - key: controller-config
                path: controller.conf
