apiVersion: v1
kind: ConfigMap
metadata:
  name: aci-containers-config
  namespace: kube-system
  labels:
    aci-containers-config-version: "c539e18b-c7bb-410b-8787-4e05c2adc52d"
    network-plugin: aci-containers
data:
  controller-config: |-
    {
        "log-level": "info",
        "apic-hosts": [
            "10.10.20.12"
        ],
        "apic-username": "kubesbx35",
        "apic-private-key-path": "/usr/local/etc/aci-cert/user.key",
        "aci-prefix": "kubesbx35",
        "aci-vmm-type": "Kubernetes",
        "aci-vmm-domain": "kubesbx35",
        "aci-vmm-controller": "kubesbx35",
        "aci-policy-tenant": "kubesbx35",
        "require-netpol-annot": false,
        "aci-service-phys-dom": "kubesbx35-pdom",
        "aci-service-encap": "vlan-973",
        "aci-service-monitor-interval": 15,
        "aci-vrf-tenant": "common",
        "aci-l3out": "sbx_shared_L3Out",
        "aci-ext-networks": [
            "any_ip"
        ],
        "aci-vrf": "sbx_shared",
        "default-endpoint-group": {
            "policy-space": "kubesbx35",
            "name": "kubernetes|kube-default"
        },
        "namespace-default-endpoint-group": {
            "kube-system": {
                "policy-space": "kubesbx35",
                "name": "kubernetes|kube-system"
            }
        },
        "service-ip-pool": [
            {
                "start": "172.20.35.194", 
                "end": "172.20.35.222"
            }
        ],
        "static-service-ip-pool": [
            {
                "start": "172.20.35.226", 
                "end": "172.20.35.254"
            }
        ],
        "pod-ip-pool": [
            {
                "start": "10.235.0.2", 
                "end": "10.235.255.254"
            }
        ],
        "node-service-ip-pool": [
            {
                "start": "192.168.135.2", 
                "end": "192.168.135.254"
            }
        ],
        "node-service-subnets": [
            "192.168.135.1/24"
        ]
    }
  host-agent-config: |-
    {
        "log-level": "info",
        "aci-vmm-type": "Kubernetes",
        "aci-vmm-domain": "kubesbx35",
        "aci-vmm-controller": "kubesbx35",
        "aci-vrf": "sbx_shared",
        "aci-vrf-tenant": "common",
        "service-vlan": 973,
        "encap-type": "vxlan",
        "aci-infra-vlan": 4093,
        "cni-netconfig": [
            {
                "routes": [
                    {
                        "gw": "10.235.0.1", 
                        "dst": "0.0.0.0/0"
                    }
                ], 
                "subnet": "10.235.0.0/16", 
                "gateway": "10.235.0.1"
            }
        ]
    }
  opflex-agent-config: |-
    {
        "log": {
            "level": "info"
        },
        "opflex": {
        }
    }
---
apiVersion: v1
kind: Secret
metadata:
  name: aci-user-cert
  namespace: kube-system
  labels:
    aci-containers-config-version: "c539e18b-c7bb-410b-8787-4e05c2adc52d"
data:
  user.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUNlQUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQW1Jd2dnSmVBZ0VBQW9HQkFOejNiSGw2VVlpVlBmWjIKSWU3ZzlqeTlDL1o0ejFXR3dickRFZE9RM0V2b2EwTHQxekxFNkh2VmJiKzdNVlgxSXdXT0JnU3pHdHE1NWdHUApWS3ZaVmNZV2FIYXRhSUdpQjV6SDRTRC9jd0VLWWRhTUp5YWozQVFtS1hxZ2todkxNTmNDbnVibVdaVEZRbjFBCmVpZ2RxblJMQ1I0dXJSMG0zbFV5OHhzQ3JkbGhBZ01CQUFFQ2dZQWF1VG0vUDFIWkNPT2ppUW4xai9OM3lRMUgKVTdrUGlPcXBJYXBvUWQ3Q3Qyc3hmdjVGdjVhMlUwdWdvbzBHN2t5OEFUOHRGbFFyRzh4N1o5QS9zRnMxRGlyTApidlJVNTFLeHYwMDNFK1VadzJjVjFpblE0MWJPN2ZoL1BXb05aZFBxU3lHSGZWWHZQY1J6ZTBQV0UxeStiTmtoCm1oZTBaVWZRSTJ4RjFpTEFXUUpCQVBvT29UQVVhRUdPM0l5UTFWaFQ2SUVDZzdiT2ZUdkRscGpHNGJxN0FQTGgKdkJ0alJUVGY2cUN5eE45cjBTb2NFVDdaOS9vR0dIK0Z1ZThCVDJaM3kvOENRUURpTjgzUGdSQkhuVmZYbTh3NwpDMGFEaC9yZ05iN0FSK1lBWXlPNGhBR1hXSmpWcXdyVWdYWllZT2xKNHpXMXBUSmFyenRLSHdaTktVWjVPV1N4CmNkcWZBa0VBejVZeGpmNkRCbG1aRWtCeVBGOThGdzJGVnM5WSs3SkZaUk5GOVlTbEp2enE4am1aREdvUEY5VVEKeHdGMHBPYWtFbTlWQTRUbjlZV0ljN2U4dUs0ZTlRSkJBS2w2VzFPcGd0UFVXbm9xdThCRWUwaVJlRysvZERCRAo3Vm0rN0lVUlNNdmxVV05LcUd0NnJub1o2TTAxVHdqT1FjSlU0OXR0RU9DQUdzODVJMm9aUFVzQ1FRRHR0WnBXCkNzSDFIdEswMGZFVVJzbkZNZzhic1FYMDdDSUxoZU1GN1grTTBiSFZHYlpjRWUrYnZKRVZnaHQyRVd1Szl6Z0sKY0JtUWNnZ2p1d1kybHZYMwotLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tCg==
  user.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUI3RENDQVZVQ0FnUG9NQTBHQ1NxR1NJYjNEUUVCQlFVQU1ENHhDekFKQmdOVkJBWVRBbFZUTVJZd0ZBWUQKVlFRS0RBMURhWE5qYnlCVGVYTjBaVzF6TVJjd0ZRWURWUVFEREE1VmMyVnlJR3QxWW1WelluZ3pOVEFlRncweApPREE0TURrd05UVTFNRFphRncweU9EQTRNRFl4TnpVMU1EWmFNRDR4Q3pBSkJnTlZCQVlUQWxWVE1SWXdGQVlEClZRUUtEQTFEYVhOamJ5QlRlWE4wWlcxek1SY3dGUVlEVlFRRERBNVZjMlZ5SUd0MVltVnpZbmd6TlRDQm56QU4KQmdrcWhraUc5dzBCQVFFRkFBT0JqUUF3Z1lrQ2dZRUEzUGRzZVhwUmlKVTk5blloN3VEMlBMMEw5bmpQVlliQgp1c01SMDVEY1MraHJRdTNYTXNUb2U5VnR2N3N4VmZVakJZNEdCTE1hMnJubUFZOVVxOWxWeGhab2RxMW9nYUlICm5NZmhJUDl6QVFwaDFvd25KcVBjQkNZcGVxQ1NHOHN3MXdLZTV1WlpsTVZDZlVCNktCMnFkRXNKSGk2dEhTYmUKVlRMekd3S3QyV0VDQXdFQUFUQU5CZ2txaGtpRzl3MEJBUVVGQUFPQmdRQUpoMmxybTRvWmJHTXRlMlpLZXQrdwpFQklpNWdNa2UwQXhnNllJaXZyek0zTGt2RkFkaVpVWGkvbldCeUN4bTBvWk1VU1d0SjZFWllMcDlMTlRQU3pTCjlXZUFxaEplTlZQamV2MVpaMWhpbm9aSGJwYnFxM2ViVWI5T1kxaVhDR0NDTXdCbFFGRTdMZ3FYdjAwV09jTjQKTXBZZmhUb2wxL3FVVlVTeVR0MDludz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aci-containers-controller
  namespace: kube-system
  labels:
    aci-containers-config-version: "c539e18b-c7bb-410b-8787-4e05c2adc52d"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aci-containers-host-agent
  namespace: kube-system
  labels:
    aci-containers-config-version: "c539e18b-c7bb-410b-8787-4e05c2adc52d"
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:
    aci-containers-config-version: "c539e18b-c7bb-410b-8787-4e05c2adc52d"
    network-plugin: aci-containers
  name: aci-containers:controller
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - namespaces
  - pods
  - endpoints
  - services
  verbs:
  - list
  - watch
  - get
- apiGroups:
  - "networking.k8s.io"
  resources:
  - networkpolicies
  verbs:
  - list
  - watch
  - get
- apiGroups:
  - "extensions"
  resources:
  - deployments
  - replicasets
  verbs:
  - list
  - watch
  - get
- apiGroups:
  - ""
  resources:
  - pods
  - nodes
  - services/status
  verbs:
  - update
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:
    aci-containers-config-version: "c539e18b-c7bb-410b-8787-4e05c2adc52d"
    network-plugin: aci-containers
  name: aci-containers:host-agent
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - pods
  - endpoints
  - services
  verbs:
  - list
  - watch
  - get
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: aci-containers:controller
  labels:
    aci-containers-config-version: "c539e18b-c7bb-410b-8787-4e05c2adc52d"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: aci-containers:controller
subjects:
- kind: ServiceAccount
  name: aci-containers-controller
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: aci-containers:host-agent
  labels:
    aci-containers-config-version: "c539e18b-c7bb-410b-8787-4e05c2adc52d"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: aci-containers:host-agent
subjects:
- kind: ServiceAccount
  name: aci-containers-host-agent
  namespace: kube-system
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: aci-containers-host
  namespace: kube-system
  labels:
    aci-containers-config-version: "c539e18b-c7bb-410b-8787-4e05c2adc52d"
    network-plugin: aci-containers
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      name: aci-containers-host
      network-plugin: aci-containers
  template:
    metadata:
      labels:
        name: aci-containers-host
        network-plugin: aci-containers
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      hostNetwork: true
      hostPID: true
      hostIPC: true
      serviceAccountName: aci-containers-host-agent
      tolerations:
        - key: CriticalAddonsOnly
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
      containers:
        - name: aci-containers-host
          image: noiro/aci-containers-host:1.7r86
          imagePullPolicy: Always
          securityContext:
            capabilities:
              add:
                - SYS_ADMIN
                - NET_ADMIN
          env:
            - name: KUBERNETES_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: cni-bin
              mountPath: /mnt/cni-bin
            - name: cni-conf
              mountPath: /mnt/cni-conf
            - name: hostvar
              mountPath: /usr/local/var
            - name: hostrun
              mountPath: /run
            - name: hostrun
              mountPath: /usr/local/run
            - name: opflex-hostconfig-volume
              mountPath: /usr/local/etc/opflex-agent-ovs/base-conf.d
            - name: host-config-volume
              mountPath: /usr/local/etc/aci-containers/
          livenessProbe:
            httpGet:
              path: /status
              port: 8090
        - name: opflex-agent
          image: noiro/opflex:1.7r70
          imagePullPolicy: Always
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          volumeMounts:
            - name: hostvar
              mountPath: /usr/local/var
            - name: hostrun
              mountPath: /run
            - name: hostrun
              mountPath: /usr/local/run
            - name: opflex-hostconfig-volume
              mountPath: /usr/local/etc/opflex-agent-ovs/base-conf.d
            - name: opflex-config-volume
              mountPath: /usr/local/etc/opflex-agent-ovs/conf.d
        - name: mcast-daemon
          image: noiro/opflex:1.7r70
          command: ["/bin/sh"]
          args: ["/usr/local/bin/launch-mcastdaemon.sh"]
          imagePullPolicy: Always
          volumeMounts:
            - name: hostvar
              mountPath: /usr/local/var
            - name: hostrun
              mountPath: /run
            - name: hostrun
              mountPath: /usr/local/run
      restartPolicy: Always
      volumes:
        - name: cni-bin
          hostPath:
            path: /opt
        - name: cni-conf
          hostPath:
            path: /etc
        - name: hostvar
          hostPath:
            path: /var
        - name: hostrun
          hostPath:
            path: /run
        - name: host-config-volume
          configMap:
            name: aci-containers-config
            items:
              - key: host-agent-config
                path: host-agent.conf
        - name: opflex-hostconfig-volume
          emptyDir:
            medium: Memory
        - name: opflex-config-volume
          configMap:
            name: aci-containers-config
            items:
              - key: opflex-agent-config
                path: local.conf
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: aci-containers-openvswitch
  namespace: kube-system
  labels:
    aci-containers-config-version: "c539e18b-c7bb-410b-8787-4e05c2adc52d"
    network-plugin: aci-containers
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      name: aci-containers-openvswitch
      network-plugin: aci-containers
  template:
    metadata:
      labels:
        name: aci-containers-openvswitch
        network-plugin: aci-containers
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      hostNetwork: true
      hostPID: true
      hostIPC: true
      serviceAccountName: aci-containers-host-agent
      tolerations:
        - key: CriticalAddonsOnly
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
      containers:
        - name: aci-containers-openvswitch
          image: noiro/openvswitch:1.7r24
          imagePullPolicy: Always
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - SYS_MODULE
                - SYS_NICE
                - IPC_LOCK
          env:
            - name: OVS_RUNDIR
              value: /usr/local/var/run/openvswitch
          volumeMounts:
            - name: hostvar
              mountPath: /usr/local/var
            - name: hostrun
              mountPath: /run
            - name: hostrun
              mountPath: /usr/local/run
            - name: hostetc
              mountPath: /usr/local/etc
            - name: hostmodules
              mountPath: /lib/modules
          livenessProbe:
            exec:
              command:
                - /usr/local/bin/liveness-ovs.sh
      restartPolicy: Always
      volumes:
        - name: hostetc
          hostPath:
            path: /etc
        - name: hostvar
          hostPath:
            path: /var
        - name: hostrun
          hostPath:
            path: /run
        - name: hostmodules
          hostPath:
            path: /lib/modules
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: aci-containers-controller
  namespace: kube-system
  labels:
    aci-containers-config-version: "c539e18b-c7bb-410b-8787-4e05c2adc52d"
    network-plugin: aci-containers
    name: aci-containers-controller
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      name: aci-containers-controller
      network-plugin: aci-containers
  template:
    metadata:
      name: aci-containers-controller
      namespace: kube-system
      labels:
        name: aci-containers-controller
        network-plugin: aci-containers
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      hostNetwork: true
      serviceAccountName: aci-containers-controller
      tolerations:
        - key: CriticalAddonsOnly
      containers:
        - name: aci-containers-controller
          image: noiro/aci-containers-controller:1.7r86
          imagePullPolicy: Always
          volumeMounts:
            - name: controller-config-volume
              mountPath: /usr/local/etc/aci-containers/
            - name: aci-user-cert-volume
              mountPath: /usr/local/etc/aci-cert/
          livenessProbe:
            httpGet:
              path: /status
              port: 8091
      volumes:
        - name: aci-user-cert-volume
          secret:
            secretName: aci-user-cert
        - name: controller-config-volume
          configMap:
            name: aci-containers-config
            items:
              - key: controller-config
                path: controller.conf
