apiVersion: v1
kind: Service
metadata:
    name: svc-hello-cisco
    labels:
        app: hello-cisco
spec:
    type: ClusterIP
    ports:
       - protocol: TCP
         port: 5000
         targetPort: 5000
    selector:
        app: hello-cisco
