apiVersion: v1
kind: Service
metadata:
    name: svc-app1
    labels:
        app: app1
spec:
    type: NodePort
    ports:
    - port: 5000
      nodePort: 30001
      protocol: TCP
    selector:
        app: app1
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: deploy-app1
spec:
    replicas: 4
    selector:
        matchLabels:
            app: app1
    minReadySeconds: 10
    strategy:
        type: RollingUpdate
        rollingUpdate:
            maxUnavailable: 1
            maxSurge: 1
    template:
        metadata:
            labels:
                app: app1
        spec:
            containers:
            - name: app1
              image: mimaurer/hello-cisco:v1
              ports:
              - containerPort: 5000
