apiVersion: v1
kind: ConfigMap
metadata:
  name: aci-containers-config
  namespace: kube-system
  labels:
    aci-containers-config-version: "eb712c40-a248-4c04-8f70-f9da015e9e38"
    network-plugin: aci-containers
data:
  controller-config: |-
    {
        "log-level": "info",
        "apic-hosts": [
            "10.10.20.12"
        ],
        "apic-username": "kubesbx16",
        "apic-private-key-path": "/usr/local/etc/aci-cert/user.key",
        "aci-prefix": "kubesbx16",
        "aci-vmm-type": "Kubernetes",
        "aci-vmm-domain": "kubesbx16",
        "aci-vmm-controller": "kubesbx16",
        "aci-policy-tenant": "kubesbx16",
        "require-netpol-annot": false,
        "aci-service-phys-dom": "kubesbx16-pdom",
        "aci-service-encap": "vlan-935",
        "aci-service-monitor-interval": 15,
        "aci-vrf-tenant": "common",
        "aci-l3out": "sbx_shared_L3Out",
        "aci-ext-networks": [
            "any_ip"
        ],
        "aci-vrf": "sbx_shared",
        "default-endpoint-group": {
            "policy-space": "kubesbx16",
            "name": "kubernetes|kube-default"
        },
        "namespace-default-endpoint-group": {
            "kube-system": {
                "policy-space": "kubesbx16",
                "name": "kubernetes|kube-system"
            }
        },
        "service-ip-pool": [
            {
                "start": "172.20.16.194", 
                "end": "172.20.16.222"
            }
        ],
        "static-service-ip-pool": [
            {
                "start": "172.20.16.226", 
                "end": "172.20.16.254"
            }
        ],
        "pod-ip-pool": [
            {
                "start": "10.216.0.2", 
                "end": "10.216.255.254"
            }
        ],
        "node-service-ip-pool": [
            {
                "start": "192.168.116.2", 
                "end": "192.168.116.254"
            }
        ],
        "node-service-subnets": [
            "192.168.116.1/24"
        ]
    }
  host-agent-config: |-
    {
        "log-level": "info",
        "aci-vmm-type": "Kubernetes",
        "aci-vmm-domain": "kubesbx16",
        "aci-vmm-controller": "kubesbx16",
        "aci-vrf": "sbx_shared",
        "aci-vrf-tenant": "common",
        "service-vlan": 935,
        "encap-type": "vxlan",
        "aci-infra-vlan": 4093,
        "cni-netconfig": [
            {
                "routes": [
                    {
                        "gw": "10.216.0.1", 
                        "dst": "0.0.0.0/0"
                    }
                ], 
                "subnet": "10.216.0.0/16", 
                "gateway": "10.216.0.1"
            }
        ]
    }
  opflex-agent-config: |-
    {
        "log": {
            "level": "info"
        },
        "opflex": {
        }
    }
---
apiVersion: v1
kind: Secret
metadata:
  name: aci-user-cert
  namespace: kube-system
  labels:
    aci-containers-config-version: "eb712c40-a248-4c04-8f70-f9da015e9e38"
data:
  user.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUNkZ0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQW1Bd2dnSmNBZ0VBQW9HQkFKOWZTUkVVSzl4dzdTQkMKNVpwU0FTZ09lWCtDRER6K2RTQU1RUEY2U20yK3ZVOWc0NEJOUjlPeEYyR2M5ME9hL3R0Tm5raG5rQitNcE1FaApncnJ6VWpGaVJVMmFWcnp5cVlEVWtZTWgrdTNxc29qTFhuOUJzcUd4NmhlSG5JWkRMWU1yTEpmOFprZGM2UEdICklQMzhaNFRRd05LYXRLSE1mb2tuSEVYR3ZadXJBZ01CQUFFQ2dZQXZycnFWdVl0RjhTT0JPNEttb1ZKblFhMW8KVU9pSWR6bGoxVWE0K1BXNzBBMmo2a0VtNmZoTGhmaVE0LzIyNUhETC9IVVhCS1ZDU3pvZjduN0dvSFkraDB4aQpFR1Vyd29udWFVS0I1T1hOQXdMUEhIMy9oMDQ0OVJIUVFiMmlkbzY4aytid3lnNUUzbW5ML1J3SzZoWEh5SEVkCkg3aUM1Mmx0ZUozUTZpUEZ3UUpCQU5HOGlaUkpkdkJOdmhodXhvTFkvMVVPdzdTdVQrMHdmM2crS2Jzc1VEWXcKU0tjU1VkcmExeFMzUHIwcEhmQ3l5MHRoMG1ldi9rMVJJNkVpcjFKdnJRY0NRUURDaHNOd1k1alc4RVdyaEQvUQpwUHo4MWZzemphb3g5emN0R2cwV0dlSUZQcEpTVndBK0xPMk90cURXbXlBell3WEtaaUtOTDloejF5bjJOblhlCkRGYzlBa0VBdEd3RXlneGNoYUhMQ29lWXV3emlzUS92YU9tZWxnTG5WTS9jNUVmZGhKQUtuN1pSdGZ3Vms1dUQKSEFSWDNpeGdWNnVCN1hKblI2bXFCYjZwcFRldVZ3SkFIVHBRYlRlWnhGblByZ2l0NmZTUVNwRUFNR3ZOc2JvNgpZUjF6NytrdHE2b09KQzhNUzB0RzJsV1lid1paM1Q2NHBRT1psMnNqODZ2Vmt6ZjFsOHAwNVFKQUxxOWMrY3k5CkR5c1pjNHJIUTMvSE9wckJqNThTUGczbFNlN2xtZkpEYzdzOW90WUtLSWZmT0FCNGh4ODFkVExkTGlkZU5WWFkKR1R6ci9WNmZ1Q2Q4NXc9PQotLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tCg==
  user.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUI3RENDQVZVQ0FnUG9NQTBHQ1NxR1NJYjNEUUVCQlFVQU1ENHhDekFKQmdOVkJBWVRBbFZUTVJZd0ZBWUQKVlFRS0RBMURhWE5qYnlCVGVYTjBaVzF6TVJjd0ZRWURWUVFEREE1VmMyVnlJR3QxWW1WelluZ3hOakFlRncweApPREE0TURrd05UVXpNREphRncweU9EQTRNRFl4TnpVek1ESmFNRDR4Q3pBSkJnTlZCQVlUQWxWVE1SWXdGQVlEClZRUUtEQTFEYVhOamJ5QlRlWE4wWlcxek1SY3dGUVlEVlFRRERBNVZjMlZ5SUd0MVltVnpZbmd4TmpDQm56QU4KQmdrcWhraUc5dzBCQVFFRkFBT0JqUUF3Z1lrQ2dZRUFuMTlKRVJRcjNIRHRJRUxsbWxJQktBNTVmNElNUFA1MQpJQXhBOFhwS2JiNjlUMkRqZ0UxSDA3RVhZWnozUTVyKzIwMmVTR2VRSDR5a3dTR0N1dk5TTVdKRlRacFd2UEtwCmdOU1JneUg2N2VxeWlNdGVmMEd5b2JIcUY0ZWNoa010Z3lzc2wveG1SMXpvOFljZy9meG5oTkRBMHBxMG9jeCsKaVNjY1JjYTltNnNDQXdFQUFUQU5CZ2txaGtpRzl3MEJBUVVGQUFPQmdRQ1RSL0R5YUtmOVlGZHFXR1dMTEtoaApMK2lSMmpReGpadE1VekIvRnBEM2JraTZDNDd1bHdNZjJEOVFaYUdrN2pnK2VzU1JqSEJSYzUzTzdkY3lNeWlsCjZCem1US1VUaDBZZlpNTkl4S3d2L0Z0N0VqM2swc1ZBV0Y3NTdJZWRVMzdEekZ3L2RvN1ZuZS9lUUM3RWh4RU8KSFQrTFprVldvYnA2c1pkWlJYOGkxUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aci-containers-controller
  namespace: kube-system
  labels:
    aci-containers-config-version: "eb712c40-a248-4c04-8f70-f9da015e9e38"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aci-containers-host-agent
  namespace: kube-system
  labels:
    aci-containers-config-version: "eb712c40-a248-4c04-8f70-f9da015e9e38"
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:
    aci-containers-config-version: "eb712c40-a248-4c04-8f70-f9da015e9e38"
    network-plugin: aci-containers
  name: aci-containers:controller
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - namespaces
  - pods
  - endpoints
  - services
  verbs:
  - list
  - watch
  - get
- apiGroups:
  - "networking.k8s.io"
  resources:
  - networkpolicies
  verbs:
  - list
  - watch
  - get
- apiGroups:
  - "extensions"
  resources:
  - deployments
  - replicasets
  verbs:
  - list
  - watch
  - get
- apiGroups:
  - ""
  resources:
  - pods
  - nodes
  - services/status
  verbs:
  - update
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:
    aci-containers-config-version: "eb712c40-a248-4c04-8f70-f9da015e9e38"
    network-plugin: aci-containers
  name: aci-containers:host-agent
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - pods
  - endpoints
  - services
  verbs:
  - list
  - watch
  - get
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: aci-containers:controller
  labels:
    aci-containers-config-version: "eb712c40-a248-4c04-8f70-f9da015e9e38"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: aci-containers:controller
subjects:
- kind: ServiceAccount
  name: aci-containers-controller
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: aci-containers:host-agent
  labels:
    aci-containers-config-version: "eb712c40-a248-4c04-8f70-f9da015e9e38"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: aci-containers:host-agent
subjects:
- kind: ServiceAccount
  name: aci-containers-host-agent
  namespace: kube-system
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: aci-containers-host
  namespace: kube-system
  labels:
    aci-containers-config-version: "eb712c40-a248-4c04-8f70-f9da015e9e38"
    network-plugin: aci-containers
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      name: aci-containers-host
      network-plugin: aci-containers
  template:
    metadata:
      labels:
        name: aci-containers-host
        network-plugin: aci-containers
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      hostNetwork: true
      hostPID: true
      hostIPC: true
      serviceAccountName: aci-containers-host-agent
      tolerations:
        - key: CriticalAddonsOnly
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
      containers:
        - name: aci-containers-host
          image: noiro/aci-containers-host:1.7r86
          imagePullPolicy: Always
          securityContext:
            capabilities:
              add:
                - SYS_ADMIN
                - NET_ADMIN
          env:
            - name: KUBERNETES_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: cni-bin
              mountPath: /mnt/cni-bin
            - name: cni-conf
              mountPath: /mnt/cni-conf
            - name: hostvar
              mountPath: /usr/local/var
            - name: hostrun
              mountPath: /run
            - name: hostrun
              mountPath: /usr/local/run
            - name: opflex-hostconfig-volume
              mountPath: /usr/local/etc/opflex-agent-ovs/base-conf.d
            - name: host-config-volume
              mountPath: /usr/local/etc/aci-containers/
          livenessProbe:
            httpGet:
              path: /status
              port: 8090
        - name: opflex-agent
          image: noiro/opflex:1.7r70
          imagePullPolicy: Always
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          volumeMounts:
            - name: hostvar
              mountPath: /usr/local/var
            - name: hostrun
              mountPath: /run
            - name: hostrun
              mountPath: /usr/local/run
            - name: opflex-hostconfig-volume
              mountPath: /usr/local/etc/opflex-agent-ovs/base-conf.d
            - name: opflex-config-volume
              mountPath: /usr/local/etc/opflex-agent-ovs/conf.d
        - name: mcast-daemon
          image: noiro/opflex:1.7r70
          command: ["/bin/sh"]
          args: ["/usr/local/bin/launch-mcastdaemon.sh"]
          imagePullPolicy: Always
          volumeMounts:
            - name: hostvar
              mountPath: /usr/local/var
            - name: hostrun
              mountPath: /run
            - name: hostrun
              mountPath: /usr/local/run
      restartPolicy: Always
      volumes:
        - name: cni-bin
          hostPath:
            path: /opt
        - name: cni-conf
          hostPath:
            path: /etc
        - name: hostvar
          hostPath:
            path: /var
        - name: hostrun
          hostPath:
            path: /run
        - name: host-config-volume
          configMap:
            name: aci-containers-config
            items:
              - key: host-agent-config
                path: host-agent.conf
        - name: opflex-hostconfig-volume
          emptyDir:
            medium: Memory
        - name: opflex-config-volume
          configMap:
            name: aci-containers-config
            items:
              - key: opflex-agent-config
                path: local.conf
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: aci-containers-openvswitch
  namespace: kube-system
  labels:
    aci-containers-config-version: "eb712c40-a248-4c04-8f70-f9da015e9e38"
    network-plugin: aci-containers
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      name: aci-containers-openvswitch
      network-plugin: aci-containers
  template:
    metadata:
      labels:
        name: aci-containers-openvswitch
        network-plugin: aci-containers
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      hostNetwork: true
      hostPID: true
      hostIPC: true
      serviceAccountName: aci-containers-host-agent
      tolerations:
        - key: CriticalAddonsOnly
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
      containers:
        - name: aci-containers-openvswitch
          image: noiro/openvswitch:1.7r24
          imagePullPolicy: Always
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - SYS_MODULE
                - SYS_NICE
                - IPC_LOCK
          env:
            - name: OVS_RUNDIR
              value: /usr/local/var/run/openvswitch
          volumeMounts:
            - name: hostvar
              mountPath: /usr/local/var
            - name: hostrun
              mountPath: /run
            - name: hostrun
              mountPath: /usr/local/run
            - name: hostetc
              mountPath: /usr/local/etc
            - name: hostmodules
              mountPath: /lib/modules
          livenessProbe:
            exec:
              command:
                - /usr/local/bin/liveness-ovs.sh
      restartPolicy: Always
      volumes:
        - name: hostetc
          hostPath:
            path: /etc
        - name: hostvar
          hostPath:
            path: /var
        - name: hostrun
          hostPath:
            path: /run
        - name: hostmodules
          hostPath:
            path: /lib/modules
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: aci-containers-controller
  namespace: kube-system
  labels:
    aci-containers-config-version: "eb712c40-a248-4c04-8f70-f9da015e9e38"
    network-plugin: aci-containers
    name: aci-containers-controller
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      name: aci-containers-controller
      network-plugin: aci-containers
  template:
    metadata:
      name: aci-containers-controller
      namespace: kube-system
      labels:
        name: aci-containers-controller
        network-plugin: aci-containers
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      hostNetwork: true
      serviceAccountName: aci-containers-controller
      tolerations:
        - key: CriticalAddonsOnly
      containers:
        - name: aci-containers-controller
          image: noiro/aci-containers-controller:1.7r86
          imagePullPolicy: Always
          volumeMounts:
            - name: controller-config-volume
              mountPath: /usr/local/etc/aci-containers/
            - name: aci-user-cert-volume
              mountPath: /usr/local/etc/aci-cert/
          livenessProbe:
            httpGet:
              path: /status
              port: 8091
      volumes:
        - name: aci-user-cert-volume
          secret:
            secretName: aci-user-cert
        - name: controller-config-volume
          configMap:
            name: aci-containers-config
            items:
              - key: controller-config
                path: controller.conf
