apiVersion: v1
kind: Service
metadata:
    name: frontend-svc
    labels:
        app: frontend
spec:
    type: NodePort
    ports:
    - port: 5000
      nodePort: 30010
      protocol: TCP
    selector:
        app: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deploy
  labels:
    app: frontend
spec:
  replicas: 4
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - image: mimaurer/frontend:v2
          name: frontend
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: C1sco123
          ports:
            - containerPort: 5000
              name: frontend
