apiVersion: v1
kind: ConfigMap
metadata:
  name: aci-containers-config
  namespace: kube-system
  labels:
    aci-containers-config-version: "d8554911-6a86-4f24-be14-0b053442d972"
    network-plugin: aci-containers
data:
  controller-config: |-
    {
        "log-level": "info",
        "apic-hosts": [
            "10.10.20.12"
        ],
        "apic-username": "kubesbx03",
        "apic-private-key-path": "/usr/local/etc/aci-cert/user.key",
        "aci-prefix": "kubesbx03",
        "aci-vmm-type": "Kubernetes",
        "aci-vmm-domain": "kubesbx03",
        "aci-vmm-controller": "kubesbx03",
        "aci-policy-tenant": "kubesbx03",
        "require-netpol-annot": false,
        "aci-service-phys-dom": "kubesbx03-pdom",
        "aci-service-encap": "vlan-909",
        "aci-service-monitor-interval": 15,
        "aci-vrf-tenant": "common",
        "aci-l3out": "sbx_shared_L3Out",
        "aci-ext-networks": [
            "any_ip"
        ],
        "aci-vrf": "sbx_shared",
        "default-endpoint-group": {
            "policy-space": "kubesbx03",
            "name": "kubernetes|kube-default"
        },
        "namespace-default-endpoint-group": {
            "kube-system": {
                "policy-space": "kubesbx03",
                "name": "kubernetes|kube-system"
            }
        },
        "service-ip-pool": [
            {
                "start": "172.20.3.194", 
                "end": "172.20.3.222"
            }
        ],
        "static-service-ip-pool": [
            {
                "start": "172.20.3.226", 
                "end": "172.20.3.254"
            }
        ],
        "pod-ip-pool": [
            {
                "start": "10.203.0.2", 
                "end": "10.203.255.254"
            }
        ],
        "node-service-ip-pool": [
            {
                "start": "192.168.103.2", 
                "end": "192.168.103.254"
            }
        ],
        "node-service-subnets": [
            "192.168.103.1/24"
        ]
    }
  host-agent-config: |-
    {
        "log-level": "info",
        "aci-vmm-type": "Kubernetes",
        "aci-vmm-domain": "kubesbx03",
        "aci-vmm-controller": "kubesbx03",
        "aci-vrf": "sbx_shared",
        "aci-vrf-tenant": "common",
        "service-vlan": 909,
        "encap-type": "vxlan",
        "aci-infra-vlan": 4093,
        "cni-netconfig": [
            {
                "routes": [
                    {
                        "gw": "10.203.0.1", 
                        "dst": "0.0.0.0/0"
                    }
                ], 
                "subnet": "10.203.0.0/16", 
                "gateway": "10.203.0.1"
            }
        ]
    }
  opflex-agent-config: |-
    {
        "log": {
            "level": "info"
        },
        "opflex": {
        }
    }
---
apiVersion: v1
kind: Secret
metadata:
  name: aci-user-cert
  namespace: kube-system
  labels:
    aci-containers-config-version: "d8554911-6a86-4f24-be14-0b053442d972"
data:
  user.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUNkZ0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQW1Bd2dnSmNBZ0VBQW9HQkFQd2NMcjh5YlI3S2luc2YKSFQ4OG9HZDl5L0JoWnQ0bzByOXRPeWpwOWUrc3lkYVdpSkdoTmt2M0ZoRTdLWXQ0ZlljMjVWdnZjQlZ5d2RnTgp4K016bFNUWVJsZmQreTh5dHNOOW1rVkpCcnB4bjIydFdtNWhzSThXeHg0elR4TUxZOXV5WmJtc2crOEhwK0s1CkwrT1AvY2NUK1F3bXhQZWhjczJUSHdLbXVjdEZBZ01CQUFFQ2dZQmFXcjltUnV4VTNNSkUzaUhkU0IwMCtpRGQKUmd0WUU4bDBVZkdoK0Rmc2JrRG9aNHNLcG55UFBUN3JiZ2kxczdsSmZLTTNEOWxiMW9VaXFjMjU0QUxUTzVYcgp3SHYvSFc4TGEwaUVhY2o5Q0pUdkJtK0VlR29zK2c1WlBzZFJ2T2NDYmlVaW1tNWQ1aEF5WTVSc25xK0svM2pECkovZHEzY3NDeUNETGE0U2dBUUpCQVA3K3FqQ29vWmtjcGVrdXA4RFJYQlA4RXJGOFpLMDlCdTk3V2p0UGU5dE8KcDJpczhJV2w3NWFqTXFUWkVINUpJbHY4OXhwVFp0UnpzWnRFZUREaDFtVUNRUUQ5R3B0TDdoeFI4dlRWeGNiVwpNQkFNaHRqeEVqd3d6YzQxL3RNcjlhVVh2Mm5Fd2F2Y0Myd0pSMkxJN2dRSnVjVDlzcytpZWJzZXVFMUpGRGxwCkhPTmhBa0JTV1pKREJxS3huUFBqMjZKbmZmVjdxc09xdUI2WGFBY09Ya3JrcnFXMFRMRjU5NmZ4c1lZdm91TGYKSkE3VWllL2p2MDFhSGljdVkzS3ZUeXgxdE9tVkFrRUF5VzB2UWhKUlAzYVhHcm0zTUNZMzM0QkJqamp3NWZZagpzaDBHZWVtWVpYblQ5dDRhbzVnRGRxNzFFdXM1RTNSZ0xYYnNmMlZaWVcxVE5HRi8vd01hZ1FKQWNhK1l1UzBJCmpFSDErSUo0YUR4SUFJK3U0VHVMc2FTZDVlWkVqRzNLai9QRGcyOFliWU5kMUhvN3E2S2xlTjJXMCtiYzRvYWcKRUZONUlOQWdvVEUxNHc9PQotLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tCg==
  user.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUI3RENDQVZVQ0FnUG9NQTBHQ1NxR1NJYjNEUUVCQlFVQU1ENHhDekFKQmdOVkJBWVRBbFZUTVJZd0ZBWUQKVlFRS0RBMURhWE5qYnlCVGVYTjBaVzF6TVJjd0ZRWURWUVFEREE1VmMyVnlJR3QxWW1WelluZ3dNekFlRncweApPREExTXpFeE5EUXhOVGRhRncweU9EQTFNamt3TWpReE5UZGFNRDR4Q3pBSkJnTlZCQVlUQWxWVE1SWXdGQVlEClZRUUtEQTFEYVhOamJ5QlRlWE4wWlcxek1SY3dGUVlEVlFRRERBNVZjMlZ5SUd0MVltVnpZbmd3TXpDQm56QU4KQmdrcWhraUc5dzBCQVFFRkFBT0JqUUF3Z1lrQ2dZRUEvQnd1dnpKdEhzcUtleDhkUHp5Z1ozM0w4R0ZtM2lqUwp2MjA3S09uMTc2ekoxcGFJa2FFMlMvY1dFVHNwaTNoOWh6YmxXKzl3RlhMQjJBM0g0ek9WSk5oR1Y5MzdMeksyCnczMmFSVWtHdW5HZmJhMWFibUd3anhiSEhqTlBFd3RqMjdKbHVheUQ3d2VuNHJrdjQ0Lzl4eFA1RENiRTk2RnkKelpNZkFxYTV5MFVDQXdFQUFUQU5CZ2txaGtpRzl3MEJBUVVGQUFPQmdRQnFuMTVZdi9MeXhCQ2FTRzhMb1pEUgo4K3YreWNkWnpERGF0RFNBb1ZwMk9mZGtmeVEra2hFMzZlS2JzczFoSGVEOURqcEdyNkhoais4Y0pFdGJiaXRZCk1sei9nSGFGaC8vRzF6dTRZcDlRei9sUmlJRHlneks5Y3AxSHF4NVNkVnMvZnl1MjFYZjhSeU82MkpMbkplSkwKVEE0OHZzdVFrTEFpekxxSFliT250Zz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aci-containers-controller
  namespace: kube-system
  labels:
    aci-containers-config-version: "d8554911-6a86-4f24-be14-0b053442d972"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aci-containers-host-agent
  namespace: kube-system
  labels:
    aci-containers-config-version: "d8554911-6a86-4f24-be14-0b053442d972"
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:
    aci-containers-config-version: "d8554911-6a86-4f24-be14-0b053442d972"
    network-plugin: aci-containers
  name: aci-containers:controller
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - namespaces
  - pods
  - endpoints
  - services
  verbs:
  - list
  - watch
  - get
- apiGroups:
  - "networking.k8s.io"
  resources:
  - networkpolicies
  verbs:
  - list
  - watch
  - get
- apiGroups:
  - "extensions"
  resources:
  - deployments
  - replicasets
  verbs:
  - list
  - watch
  - get
- apiGroups:
  - ""
  resources:
  - pods
  - nodes
  - services/status
  verbs:
  - update
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:
    aci-containers-config-version: "d8554911-6a86-4f24-be14-0b053442d972"
    network-plugin: aci-containers
  name: aci-containers:host-agent
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - pods
  - endpoints
  - services
  verbs:
  - list
  - watch
  - get
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: aci-containers:controller
  labels:
    aci-containers-config-version: "d8554911-6a86-4f24-be14-0b053442d972"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: aci-containers:controller
subjects:
- kind: ServiceAccount
  name: aci-containers-controller
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: aci-containers:host-agent
  labels:
    aci-containers-config-version: "d8554911-6a86-4f24-be14-0b053442d972"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: aci-containers:host-agent
subjects:
- kind: ServiceAccount
  name: aci-containers-host-agent
  namespace: kube-system
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: aci-containers-host
  namespace: kube-system
  labels:
    aci-containers-config-version: "d8554911-6a86-4f24-be14-0b053442d972"
    network-plugin: aci-containers
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      name: aci-containers-host
      network-plugin: aci-containers
  template:
    metadata:
      labels:
        name: aci-containers-host
        network-plugin: aci-containers
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      hostNetwork: true
      hostPID: true
      hostIPC: true
      serviceAccountName: aci-containers-host-agent
      tolerations:
        - key: CriticalAddonsOnly
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
      containers:
        - name: aci-containers-host
          image: noiro/aci-containers-host:1.7r86
          imagePullPolicy: Always
          securityContext:
            capabilities:
              add:
                - SYS_ADMIN
                - NET_ADMIN
          env:
            - name: KUBERNETES_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: cni-bin
              mountPath: /mnt/cni-bin
            - name: cni-conf
              mountPath: /mnt/cni-conf
            - name: hostvar
              mountPath: /usr/local/var
            - name: hostrun
              mountPath: /run
            - name: hostrun
              mountPath: /usr/local/run
            - name: opflex-hostconfig-volume
              mountPath: /usr/local/etc/opflex-agent-ovs/base-conf.d
            - name: host-config-volume
              mountPath: /usr/local/etc/aci-containers/
          livenessProbe:
            httpGet:
              path: /status
              port: 8090
        - name: opflex-agent
          image: noiro/opflex:1.7r70
          imagePullPolicy: Always
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          volumeMounts:
            - name: hostvar
              mountPath: /usr/local/var
            - name: hostrun
              mountPath: /run
            - name: hostrun
              mountPath: /usr/local/run
            - name: opflex-hostconfig-volume
              mountPath: /usr/local/etc/opflex-agent-ovs/base-conf.d
            - name: opflex-config-volume
              mountPath: /usr/local/etc/opflex-agent-ovs/conf.d
        - name: mcast-daemon
          image: noiro/opflex:1.7r70
          command: ["/bin/sh"]
          args: ["/usr/local/bin/launch-mcastdaemon.sh"]
          imagePullPolicy: Always
          volumeMounts:
            - name: hostvar
              mountPath: /usr/local/var
            - name: hostrun
              mountPath: /run
            - name: hostrun
              mountPath: /usr/local/run
      restartPolicy: Always
      volumes:
        - name: cni-bin
          hostPath:
            path: /opt
        - name: cni-conf
          hostPath:
            path: /etc
        - name: hostvar
          hostPath:
            path: /var
        - name: hostrun
          hostPath:
            path: /run
        - name: host-config-volume
          configMap:
            name: aci-containers-config
            items:
              - key: host-agent-config
                path: host-agent.conf
        - name: opflex-hostconfig-volume
          emptyDir:
            medium: Memory
        - name: opflex-config-volume
          configMap:
            name: aci-containers-config
            items:
              - key: opflex-agent-config
                path: local.conf
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: aci-containers-openvswitch
  namespace: kube-system
  labels:
    aci-containers-config-version: "d8554911-6a86-4f24-be14-0b053442d972"
    network-plugin: aci-containers
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      name: aci-containers-openvswitch
      network-plugin: aci-containers
  template:
    metadata:
      labels:
        name: aci-containers-openvswitch
        network-plugin: aci-containers
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      hostNetwork: true
      hostPID: true
      hostIPC: true
      serviceAccountName: aci-containers-host-agent
      tolerations:
        - key: CriticalAddonsOnly
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
      containers:
        - name: aci-containers-openvswitch
          image: noiro/openvswitch:1.7r24
          imagePullPolicy: Always
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - SYS_MODULE
                - SYS_NICE
                - IPC_LOCK
          env:
            - name: OVS_RUNDIR
              value: /usr/local/var/run/openvswitch
          volumeMounts:
            - name: hostvar
              mountPath: /usr/local/var
            - name: hostrun
              mountPath: /run
            - name: hostrun
              mountPath: /usr/local/run
            - name: hostetc
              mountPath: /usr/local/etc
            - name: hostmodules
              mountPath: /lib/modules
          livenessProbe:
            exec:
              command:
                - /usr/local/bin/liveness-ovs.sh
      restartPolicy: Always
      volumes:
        - name: hostetc
          hostPath:
            path: /etc
        - name: hostvar
          hostPath:
            path: /var
        - name: hostrun
          hostPath:
            path: /run
        - name: hostmodules
          hostPath:
            path: /lib/modules
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: aci-containers-controller
  namespace: kube-system
  labels:
    aci-containers-config-version: "d8554911-6a86-4f24-be14-0b053442d972"
    network-plugin: aci-containers
    name: aci-containers-controller
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      name: aci-containers-controller
      network-plugin: aci-containers
  template:
    metadata:
      name: aci-containers-controller
      namespace: kube-system
      labels:
        name: aci-containers-controller
        network-plugin: aci-containers
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      hostNetwork: true
      serviceAccountName: aci-containers-controller
      tolerations:
        - key: CriticalAddonsOnly
      containers:
        - name: aci-containers-controller
          image: noiro/aci-containers-controller:1.7r86
          imagePullPolicy: Always
          volumeMounts:
            - name: controller-config-volume
              mountPath: /usr/local/etc/aci-containers/
            - name: aci-user-cert-volume
              mountPath: /usr/local/etc/aci-cert/
          livenessProbe:
            httpGet:
              path: /status
              port: 8091
      volumes:
        - name: aci-user-cert-volume
          secret:
            secretName: aci-user-cert
        - name: controller-config-volume
          configMap:
            name: aci-containers-config
            items:
              - key: controller-config
                path: controller.conf
