apiVersion: v1
kind: ConfigMap
metadata:
  name: aci-containers-config
  namespace: kube-system
  labels:
    aci-containers-config-version: "77976596-a964-4a70-881a-776366f3675b"
    network-plugin: aci-containers
data:
  controller-config: |-
    {
        "log-level": "info",
        "apic-hosts": [
            "10.10.20.12"
        ],
        "apic-username": "kubesbx22",
        "apic-private-key-path": "/usr/local/etc/aci-cert/user.key",
        "aci-prefix": "kubesbx22",
        "aci-vmm-type": "Kubernetes",
        "aci-vmm-domain": "kubesbx22",
        "aci-vmm-controller": "kubesbx22",
        "aci-policy-tenant": "kubesbx22",
        "require-netpol-annot": false,
        "aci-service-phys-dom": "kubesbx22-pdom",
        "aci-service-encap": "vlan-947",
        "aci-service-monitor-interval": 15,
        "aci-vrf-tenant": "common",
        "aci-l3out": "sbx_shared_L3Out",
        "aci-ext-networks": [
            "any_ip"
        ],
        "aci-vrf": "sbx_shared",
        "default-endpoint-group": {
            "policy-space": "kubesbx22",
            "name": "kubernetes|kube-default"
        },
        "namespace-default-endpoint-group": {
            "kube-system": {
                "policy-space": "kubesbx22",
                "name": "kubernetes|kube-system"
            }
        },
        "service-ip-pool": [
            {
                "start": "172.20.22.194", 
                "end": "172.20.22.222"
            }
        ],
        "static-service-ip-pool": [
            {
                "start": "172.20.22.226", 
                "end": "172.20.22.254"
            }
        ],
        "pod-ip-pool": [
            {
                "start": "10.222.0.2", 
                "end": "10.222.255.254"
            }
        ],
        "node-service-ip-pool": [
            {
                "start": "192.168.122.2", 
                "end": "192.168.122.254"
            }
        ],
        "node-service-subnets": [
            "192.168.122.1/24"
        ]
    }
  host-agent-config: |-
    {
        "log-level": "info",
        "aci-vmm-type": "Kubernetes",
        "aci-vmm-domain": "kubesbx22",
        "aci-vmm-controller": "kubesbx22",
        "aci-vrf": "sbx_shared",
        "aci-vrf-tenant": "common",
        "service-vlan": 947,
        "encap-type": "vxlan",
        "aci-infra-vlan": 4093,
        "cni-netconfig": [
            {
                "routes": [
                    {
                        "gw": "10.222.0.1", 
                        "dst": "0.0.0.0/0"
                    }
                ], 
                "subnet": "10.222.0.0/16", 
                "gateway": "10.222.0.1"
            }
        ]
    }
  opflex-agent-config: |-
    {
        "log": {
            "level": "info"
        },
        "opflex": {
        }
    }
---
apiVersion: v1
kind: Secret
metadata:
  name: aci-user-cert
  namespace: kube-system
  labels:
    aci-containers-config-version: "77976596-a964-4a70-881a-776366f3675b"
data:
  user.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUNkd0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQW1Fd2dnSmRBZ0VBQW9HQkFMZXF5VzBYcXFxVFpFWHkKaG9XakY4dzJ3dG5FdEZCUld6S1plSEwvN21iaGVDc0Vmd0EvenVVY3ZQTE5wUXVFTWJYUWU3MG93WUVLakVYTwpsOXVJV1dsUTZMK3dhSnRBTlNHbFcxVGxURmZaK2Q2UnliRldWTEdyNC9tZExLU0ZqTEVpV2RQeVl1NEJEK1lRCnREZDFJNVduN3lRSlVKU21zaWZxNXl0bVR1UVBBZ01CQUFFQ2dZRUFuRHZIUStsUjMrK282R2M1VHd4QS9oSEgKQmY5eGNyRUI1clR0NU1VWVFxT2cyTmJtUVl3RnJwY1hrMktpOW56bzNFUVFQZ1FoTm1lR2t3cjkybHpOMEhxVwpWVXNwWHJkdkhiOHF6NjF1bDUwbmVUUlFxeE1DUW90dkhGQnlTOUVaM1RxQU1iampMU1NlR2RlMmhVQlQ4UGd1CnJ0YWkyL01pS0RNalQzU25Md0VDUVFEb21mU2xZYzduRkVLc1BpMUg0L0NhMHZJNVB5amRVTWZObE01SW5uS2IKUTJjbnRWb3IxVFh4ci9URFdqbmwrSFdkUVo0Z21lNWxsQ3FmclJqc0UxVXZBa0VBeWlTb0dYMFUrUmNUUWVNRwpMdTRWWVVqZ0ljSVFRTkgvNG1FaWVwRGsyQ0Z2OGQvTjgvQU56ZmZ0K0Jvc245SzJWTWNGMjJndnJXaEs1TytGCmUyVm5JUUpBV1RDL3VMTGFqWTBkUzhMRHhpOUhVWGJWM3RHekw3b01BMjZ0OHZhZTU1NWU3Y0VDaEpCTEVSUHgKZlA4WitHN2ZXcCtRck51WnFHVzZPbVE3akRxVmpRSkJBTGVxNU4zNzY4R0QrT2hsdWFtTWcvcVg5NlpVcU9YcwpxUjVzK2FINTR5U0tCU2YxSFRHbkRUUDNNTTY4SVkyNkxCY05tc0hIZ1lLQy80SFNMQ3Q1Y0dFQ1FBZjVNQkgxCmdkcUwvVW9sM0hSOVJLeDlpZEhkZDNkdDBmQXZ3M1BZRDFGeUlOdUN5bDBqYm8vaWR3K0I5aTdKcitVaHk3b2UKb3p5c3NJcjZjeXU0Nmk0PQotLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tCg==
  user.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUI3RENDQVZVQ0FnUG9NQTBHQ1NxR1NJYjNEUUVCQlFVQU1ENHhDekFKQmdOVkJBWVRBbFZUTVJZd0ZBWUQKVlFRS0RBMURhWE5qYnlCVGVYTjBaVzF6TVJjd0ZRWURWUVFEREE1VmMyVnlJR3QxWW1WelluZ3lNakFlRncweApPREE0TURrd05UVXpOREZhRncweU9EQTRNRFl4TnpVek5ERmFNRDR4Q3pBSkJnTlZCQVlUQWxWVE1SWXdGQVlEClZRUUtEQTFEYVhOamJ5QlRlWE4wWlcxek1SY3dGUVlEVlFRRERBNVZjMlZ5SUd0MVltVnpZbmd5TWpDQm56QU4KQmdrcWhraUc5dzBCQVFFRkFBT0JqUUF3Z1lrQ2dZRUF0NnJKYlJlcXFwTmtSZktHaGFNWHpEYkMyY1MwVUZGYgpNcGw0Y3YvdVp1RjRLd1IvQUQvTzVSeTg4czJsQzRReHRkQjd2U2pCZ1FxTVJjNlgyNGhaYVZEb3Y3Qm9tMEExCklhVmJWT1ZNVjluNTNwSEpzVlpVc2F2aitaMHNwSVdNc1NKWjAvSmk3Z0VQNWhDME4zVWpsYWZ2SkFsUWxLYXkKSitybksyWk81QThDQXdFQUFUQU5CZ2txaGtpRzl3MEJBUVVGQUFPQmdRQ3V1U1M2c1oybktNbUx2bzNuazB6NQo4R0dkMGtXR3k0YWFOZTRzeDVYenM4L1VjOGdpZmc3RXVYZUlhcDFFc0lCbDI5OThnZkJhWWJWd0prT1UvdFZOCk55SlhVUnRNTHBiM2VoTDVVWVF4TVNJZWtMTmEvWlE5VEI3QUtQVEQ1UE93Misyb0NGbDNWZlZUVVlLcURZVG0KVWl4MHhpS2x0VTl6MHNZR1gwVUp2Zz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aci-containers-controller
  namespace: kube-system
  labels:
    aci-containers-config-version: "77976596-a964-4a70-881a-776366f3675b"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aci-containers-host-agent
  namespace: kube-system
  labels:
    aci-containers-config-version: "77976596-a964-4a70-881a-776366f3675b"
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:
    aci-containers-config-version: "77976596-a964-4a70-881a-776366f3675b"
    network-plugin: aci-containers
  name: aci-containers:controller
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - namespaces
  - pods
  - endpoints
  - services
  verbs:
  - list
  - watch
  - get
- apiGroups:
  - "networking.k8s.io"
  resources:
  - networkpolicies
  verbs:
  - list
  - watch
  - get
- apiGroups:
  - "extensions"
  resources:
  - deployments
  - replicasets
  verbs:
  - list
  - watch
  - get
- apiGroups:
  - ""
  resources:
  - pods
  - nodes
  - services/status
  verbs:
  - update
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:
    aci-containers-config-version: "77976596-a964-4a70-881a-776366f3675b"
    network-plugin: aci-containers
  name: aci-containers:host-agent
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - pods
  - endpoints
  - services
  verbs:
  - list
  - watch
  - get
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: aci-containers:controller
  labels:
    aci-containers-config-version: "77976596-a964-4a70-881a-776366f3675b"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: aci-containers:controller
subjects:
- kind: ServiceAccount
  name: aci-containers-controller
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: aci-containers:host-agent
  labels:
    aci-containers-config-version: "77976596-a964-4a70-881a-776366f3675b"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: aci-containers:host-agent
subjects:
- kind: ServiceAccount
  name: aci-containers-host-agent
  namespace: kube-system
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: aci-containers-host
  namespace: kube-system
  labels:
    aci-containers-config-version: "77976596-a964-4a70-881a-776366f3675b"
    network-plugin: aci-containers
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      name: aci-containers-host
      network-plugin: aci-containers
  template:
    metadata:
      labels:
        name: aci-containers-host
        network-plugin: aci-containers
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      hostNetwork: true
      hostPID: true
      hostIPC: true
      serviceAccountName: aci-containers-host-agent
      tolerations:
        - key: CriticalAddonsOnly
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
      containers:
        - name: aci-containers-host
          image: noiro/aci-containers-host:1.7r86
          imagePullPolicy: Always
          securityContext:
            capabilities:
              add:
                - SYS_ADMIN
                - NET_ADMIN
          env:
            - name: KUBERNETES_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: cni-bin
              mountPath: /mnt/cni-bin
            - name: cni-conf
              mountPath: /mnt/cni-conf
            - name: hostvar
              mountPath: /usr/local/var
            - name: hostrun
              mountPath: /run
            - name: hostrun
              mountPath: /usr/local/run
            - name: opflex-hostconfig-volume
              mountPath: /usr/local/etc/opflex-agent-ovs/base-conf.d
            - name: host-config-volume
              mountPath: /usr/local/etc/aci-containers/
          livenessProbe:
            httpGet:
              path: /status
              port: 8090
        - name: opflex-agent
          image: noiro/opflex:1.7r70
          imagePullPolicy: Always
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          volumeMounts:
            - name: hostvar
              mountPath: /usr/local/var
            - name: hostrun
              mountPath: /run
            - name: hostrun
              mountPath: /usr/local/run
            - name: opflex-hostconfig-volume
              mountPath: /usr/local/etc/opflex-agent-ovs/base-conf.d
            - name: opflex-config-volume
              mountPath: /usr/local/etc/opflex-agent-ovs/conf.d
        - name: mcast-daemon
          image: noiro/opflex:1.7r70
          command: ["/bin/sh"]
          args: ["/usr/local/bin/launch-mcastdaemon.sh"]
          imagePullPolicy: Always
          volumeMounts:
            - name: hostvar
              mountPath: /usr/local/var
            - name: hostrun
              mountPath: /run
            - name: hostrun
              mountPath: /usr/local/run
      restartPolicy: Always
      volumes:
        - name: cni-bin
          hostPath:
            path: /opt
        - name: cni-conf
          hostPath:
            path: /etc
        - name: hostvar
          hostPath:
            path: /var
        - name: hostrun
          hostPath:
            path: /run
        - name: host-config-volume
          configMap:
            name: aci-containers-config
            items:
              - key: host-agent-config
                path: host-agent.conf
        - name: opflex-hostconfig-volume
          emptyDir:
            medium: Memory
        - name: opflex-config-volume
          configMap:
            name: aci-containers-config
            items:
              - key: opflex-agent-config
                path: local.conf
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: aci-containers-openvswitch
  namespace: kube-system
  labels:
    aci-containers-config-version: "77976596-a964-4a70-881a-776366f3675b"
    network-plugin: aci-containers
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      name: aci-containers-openvswitch
      network-plugin: aci-containers
  template:
    metadata:
      labels:
        name: aci-containers-openvswitch
        network-plugin: aci-containers
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      hostNetwork: true
      hostPID: true
      hostIPC: true
      serviceAccountName: aci-containers-host-agent
      tolerations:
        - key: CriticalAddonsOnly
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
      containers:
        - name: aci-containers-openvswitch
          image: noiro/openvswitch:1.7r24
          imagePullPolicy: Always
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - SYS_MODULE
                - SYS_NICE
                - IPC_LOCK
          env:
            - name: OVS_RUNDIR
              value: /usr/local/var/run/openvswitch
          volumeMounts:
            - name: hostvar
              mountPath: /usr/local/var
            - name: hostrun
              mountPath: /run
            - name: hostrun
              mountPath: /usr/local/run
            - name: hostetc
              mountPath: /usr/local/etc
            - name: hostmodules
              mountPath: /lib/modules
          livenessProbe:
            exec:
              command:
                - /usr/local/bin/liveness-ovs.sh
      restartPolicy: Always
      volumes:
        - name: hostetc
          hostPath:
            path: /etc
        - name: hostvar
          hostPath:
            path: /var
        - name: hostrun
          hostPath:
            path: /run
        - name: hostmodules
          hostPath:
            path: /lib/modules
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: aci-containers-controller
  namespace: kube-system
  labels:
    aci-containers-config-version: "77976596-a964-4a70-881a-776366f3675b"
    network-plugin: aci-containers
    name: aci-containers-controller
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      name: aci-containers-controller
      network-plugin: aci-containers
  template:
    metadata:
      name: aci-containers-controller
      namespace: kube-system
      labels:
        name: aci-containers-controller
        network-plugin: aci-containers
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      hostNetwork: true
      serviceAccountName: aci-containers-controller
      tolerations:
        - key: CriticalAddonsOnly
      containers:
        - name: aci-containers-controller
          image: noiro/aci-containers-controller:1.7r86
          imagePullPolicy: Always
          volumeMounts:
            - name: controller-config-volume
              mountPath: /usr/local/etc/aci-containers/
            - name: aci-user-cert-volume
              mountPath: /usr/local/etc/aci-cert/
          livenessProbe:
            httpGet:
              path: /status
              port: 8091
      volumes:
        - name: aci-user-cert-volume
          secret:
            secretName: aci-user-cert
        - name: controller-config-volume
          configMap:
            name: aci-containers-config
            items:
              - key: controller-config
                path: controller.conf
