apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: k8s-with-sa
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: k8s-with-sa
    spec:
      serviceAccountName: myaccount
      containers:
      - name: k8s-with-sa
        imagePullPolicy: Always
        image: mimaurer/cisco-kubectl
        command:
        - sleep
        - "3600"
        ports:
        - name: app
          containerPort: 3000
