apiVersion: v1
kind: ConfigMap
metadata:
  name: aci-containers-config
  namespace: kube-system
  labels:
    aci-containers-config-version: "6627d4d9-50a5-4674-896e-76403290b8f4"
    network-plugin: aci-containers
data:
  controller-config: |-
    {
        "log-level": "info",
        "apic-hosts": [
            "10.10.20.12"
        ],
        "apic-username": "kubesbx43",
        "apic-private-key-path": "/usr/local/etc/aci-cert/user.key",
        "aci-prefix": "kubesbx43",
        "aci-vmm-type": "Kubernetes",
        "aci-vmm-domain": "kubesbx43",
        "aci-vmm-controller": "kubesbx43",
        "aci-policy-tenant": "kubesbx43",
        "require-netpol-annot": false,
        "aci-service-phys-dom": "kubesbx43-pdom",
        "aci-service-encap": "vlan-989",
        "aci-service-monitor-interval": 15,
        "aci-vrf-tenant": "common",
        "aci-l3out": "sbx_shared_L3Out",
        "aci-ext-networks": [
            "any_ip"
        ],
        "aci-vrf": "sbx_shared",
        "default-endpoint-group": {
            "policy-space": "kubesbx43",
            "name": "kubernetes|kube-default"
        },
        "namespace-default-endpoint-group": {
            "kube-system": {
                "policy-space": "kubesbx43",
                "name": "kubernetes|kube-system"
            }
        },
        "service-ip-pool": [
            {
                "start": "172.20.43.194", 
                "end": "172.20.43.222"
            }
        ],
        "static-service-ip-pool": [
            {
                "start": "172.20.43.226", 
                "end": "172.20.43.254"
            }
        ],
        "pod-ip-pool": [
            {
                "start": "10.243.0.2", 
                "end": "10.243.255.254"
            }
        ],
        "node-service-ip-pool": [
            {
                "start": "192.168.143.2", 
                "end": "192.168.143.254"
            }
        ],
        "node-service-subnets": [
            "192.168.143.1/24"
        ]
    }
  host-agent-config: |-
    {
        "log-level": "info",
        "aci-vmm-type": "Kubernetes",
        "aci-vmm-domain": "kubesbx43",
        "aci-vmm-controller": "kubesbx43",
        "aci-vrf": "sbx_shared",
        "aci-vrf-tenant": "common",
        "service-vlan": 989,
        "encap-type": "vxlan",
        "aci-infra-vlan": 4093,
        "cni-netconfig": [
            {
                "routes": [
                    {
                        "gw": "10.243.0.1", 
                        "dst": "0.0.0.0/0"
                    }
                ], 
                "subnet": "10.243.0.0/16", 
                "gateway": "10.243.0.1"
            }
        ]
    }
  opflex-agent-config: |-
    {
        "log": {
            "level": "info"
        },
        "opflex": {
        }
    }
---
apiVersion: v1
kind: Secret
metadata:
  name: aci-user-cert
  namespace: kube-system
  labels:
    aci-containers-config-version: "6627d4d9-50a5-4674-896e-76403290b8f4"
data:
  user.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUNkUUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQWw4d2dnSmJBZ0VBQW9HQkFMTmt4aTQyNDRsUnpKa3oKbFdDOTNBTVJ0ayt4aUJ6d3hWTGVnRmt5QjhtcW5RSUV5NnFoWFJHQjFRRXBDR1lYR1Vpc2VFUDVoaWQyeU9JVwpzZVU3c2lyaVIwcTUrVXdKZzI2OEM0SFdseE1LRDJkMllTdkFzbVQrUGVCdHNzMEZNZXVyYWlXT1JkTkdKK2xvCkR2VnppUHBqcldoY1NxaTg3VTdQNWNYRGRPWHRBZ01CQUFFQ2dZQXcxVTNkWnJPcHZjcWtLWmFRTHg2azl6MVoKbEVvcEZxR2dYVkV5OXB1SUdobURZeXJOMS84dHRObjI1dVNTWmRkTUlTYmIyaURhdlVzUndIdk1tdU4wdEM3MwpXRzhNRVRGSURBVmlaek1sZG5wNWh6OFArU0QvWnRQQzlMYWoxRXp1YURnNmVZb01ZUzF3YTBTNldGdUlVZE5RCjhyZTFhVmMreHRyRkpEbkNBUUpCQU9IU01yZWFHUE53L1ZxakM2OTkxc2pHaWlQZTY4UGdvMFVYeUVhZW4xbzYKc0tmZGdEWTdDeXVSbWxmcTZKd2ZaYTQ5eFhnQk1keHNJdU8wSlh1b2p6a0NRUURMWGpMRUR6eEVRa3ZEOFJnUgpOUkIrVzdEOFNXK2dSekFML05zd0gvNnNWUmk2NXRhdWlQbUpISm1Pa3hnaUxTLzBMYlBMbUk3NE0zT1ZmNzhQCmtCaFZBa0JDcG5hZnFCUzdMVnNwdUR2SHRSMkNyczZ3M2FlNmJYL2k4YTBENHVkbml6RCtxcXFmMXZkcUNaU0QKWkdyNVFXOFNhVnJ5RzNBcS9hT2lqMVlNMUdoSkFrQWJONkV0c2loTHJsKzdlcEhSQTd3UVhTOGpwS1JtM0FBbgpLcEVmTUxrQjBXVzg1ZFlIaDlkMXJUa3o1cVhOTlNUODFmMEJHNHJPMXZ2Nkh4MnY5SVg5QWtBOW82WVk1Qy8wClc5RFhVRkp3eUdSR2crNzFDTlJDdUl0U05wVDNFcWtOUUV5aWVLaXBKV0tTNzRGY2djb3dIRUJCamhlWmdtRGUKb0grMGRGMWNqTzJICi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K
  user.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUI3RENDQVZVQ0FnUG9NQTBHQ1NxR1NJYjNEUUVCQlFVQU1ENHhDekFKQmdOVkJBWVRBbFZUTVJZd0ZBWUQKVlFRS0RBMURhWE5qYnlCVGVYTjBaVzF6TVJjd0ZRWURWUVFEREE1VmMyVnlJR3QxWW1WelluZzBNekFlRncweApPREE0TURrd05UVTFOVGxhRncweU9EQTRNRFl4TnpVMU5UbGFNRDR4Q3pBSkJnTlZCQVlUQWxWVE1SWXdGQVlEClZRUUtEQTFEYVhOamJ5QlRlWE4wWlcxek1SY3dGUVlEVlFRRERBNVZjMlZ5SUd0MVltVnpZbmcwTXpDQm56QU4KQmdrcWhraUc5dzBCQVFFRkFBT0JqUUF3Z1lrQ2dZRUFzMlRHTGpiamlWSE1tVE9WWUwzY0F4RzJUN0dJSFBERgpVdDZBV1RJSHlhcWRBZ1RMcXFGZEVZSFZBU2tJWmhjWlNLeDRRL21HSjNiSTRoYXg1VHV5S3VKSFNybjVUQW1ECmJyd0xnZGFYRXdvUFozWmhLOEN5WlA0OTRHMnl6UVV4NjZ0cUpZNUYwMFluNldnTzlYT0krbU90YUZ4S3FMenQKVHMvbHhjTjA1ZTBDQXdFQUFUQU5CZ2txaGtpRzl3MEJBUVVGQUFPQmdRQTBwUVZwMU9vSDUzMUlVazhqcWdrWApkWHNlY044Z3d4clBLWkh4RlFWL2xpa3EzVWNSWTdCZFR4dmxiMlNCWXNxRlZDVHk4VzZFRDYvUDFUVlc3S0E0Ci9tZlBjSTljNmlSUmE0dmpHQUl1eDhKNUhwNklIRlVsdTN4ZTlzdE1xTHl2OG1BUFRUQjNTQitvaG1DVEdBNHAKVnhmM0FIVnB4R3pYYVNEbUwyYkxBQT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aci-containers-controller
  namespace: kube-system
  labels:
    aci-containers-config-version: "6627d4d9-50a5-4674-896e-76403290b8f4"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aci-containers-host-agent
  namespace: kube-system
  labels:
    aci-containers-config-version: "6627d4d9-50a5-4674-896e-76403290b8f4"
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:
    aci-containers-config-version: "6627d4d9-50a5-4674-896e-76403290b8f4"
    network-plugin: aci-containers
  name: aci-containers:controller
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - namespaces
  - pods
  - endpoints
  - services
  verbs:
  - list
  - watch
  - get
- apiGroups:
  - "networking.k8s.io"
  resources:
  - networkpolicies
  verbs:
  - list
  - watch
  - get
- apiGroups:
  - "extensions"
  resources:
  - deployments
  - replicasets
  verbs:
  - list
  - watch
  - get
- apiGroups:
  - ""
  resources:
  - pods
  - nodes
  - services/status
  verbs:
  - update
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:
    aci-containers-config-version: "6627d4d9-50a5-4674-896e-76403290b8f4"
    network-plugin: aci-containers
  name: aci-containers:host-agent
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - pods
  - endpoints
  - services
  verbs:
  - list
  - watch
  - get
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: aci-containers:controller
  labels:
    aci-containers-config-version: "6627d4d9-50a5-4674-896e-76403290b8f4"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: aci-containers:controller
subjects:
- kind: ServiceAccount
  name: aci-containers-controller
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: aci-containers:host-agent
  labels:
    aci-containers-config-version: "6627d4d9-50a5-4674-896e-76403290b8f4"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: aci-containers:host-agent
subjects:
- kind: ServiceAccount
  name: aci-containers-host-agent
  namespace: kube-system
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: aci-containers-host
  namespace: kube-system
  labels:
    aci-containers-config-version: "6627d4d9-50a5-4674-896e-76403290b8f4"
    network-plugin: aci-containers
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      name: aci-containers-host
      network-plugin: aci-containers
  template:
    metadata:
      labels:
        name: aci-containers-host
        network-plugin: aci-containers
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      hostNetwork: true
      hostPID: true
      hostIPC: true
      serviceAccountName: aci-containers-host-agent
      tolerations:
        - key: CriticalAddonsOnly
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
      containers:
        - name: aci-containers-host
          image: noiro/aci-containers-host:1.7r86
          imagePullPolicy: Always
          securityContext:
            capabilities:
              add:
                - SYS_ADMIN
                - NET_ADMIN
          env:
            - name: KUBERNETES_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: cni-bin
              mountPath: /mnt/cni-bin
            - name: cni-conf
              mountPath: /mnt/cni-conf
            - name: hostvar
              mountPath: /usr/local/var
            - name: hostrun
              mountPath: /run
            - name: hostrun
              mountPath: /usr/local/run
            - name: opflex-hostconfig-volume
              mountPath: /usr/local/etc/opflex-agent-ovs/base-conf.d
            - name: host-config-volume
              mountPath: /usr/local/etc/aci-containers/
          livenessProbe:
            httpGet:
              path: /status
              port: 8090
        - name: opflex-agent
          image: noiro/opflex:1.7r70
          imagePullPolicy: Always
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          volumeMounts:
            - name: hostvar
              mountPath: /usr/local/var
            - name: hostrun
              mountPath: /run
            - name: hostrun
              mountPath: /usr/local/run
            - name: opflex-hostconfig-volume
              mountPath: /usr/local/etc/opflex-agent-ovs/base-conf.d
            - name: opflex-config-volume
              mountPath: /usr/local/etc/opflex-agent-ovs/conf.d
        - name: mcast-daemon
          image: noiro/opflex:1.7r70
          command: ["/bin/sh"]
          args: ["/usr/local/bin/launch-mcastdaemon.sh"]
          imagePullPolicy: Always
          volumeMounts:
            - name: hostvar
              mountPath: /usr/local/var
            - name: hostrun
              mountPath: /run
            - name: hostrun
              mountPath: /usr/local/run
      restartPolicy: Always
      volumes:
        - name: cni-bin
          hostPath:
            path: /opt
        - name: cni-conf
          hostPath:
            path: /etc
        - name: hostvar
          hostPath:
            path: /var
        - name: hostrun
          hostPath:
            path: /run
        - name: host-config-volume
          configMap:
            name: aci-containers-config
            items:
              - key: host-agent-config
                path: host-agent.conf
        - name: opflex-hostconfig-volume
          emptyDir:
            medium: Memory
        - name: opflex-config-volume
          configMap:
            name: aci-containers-config
            items:
              - key: opflex-agent-config
                path: local.conf
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: aci-containers-openvswitch
  namespace: kube-system
  labels:
    aci-containers-config-version: "6627d4d9-50a5-4674-896e-76403290b8f4"
    network-plugin: aci-containers
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      name: aci-containers-openvswitch
      network-plugin: aci-containers
  template:
    metadata:
      labels:
        name: aci-containers-openvswitch
        network-plugin: aci-containers
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      hostNetwork: true
      hostPID: true
      hostIPC: true
      serviceAccountName: aci-containers-host-agent
      tolerations:
        - key: CriticalAddonsOnly
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
      containers:
        - name: aci-containers-openvswitch
          image: noiro/openvswitch:1.7r24
          imagePullPolicy: Always
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - SYS_MODULE
                - SYS_NICE
                - IPC_LOCK
          env:
            - name: OVS_RUNDIR
              value: /usr/local/var/run/openvswitch
          volumeMounts:
            - name: hostvar
              mountPath: /usr/local/var
            - name: hostrun
              mountPath: /run
            - name: hostrun
              mountPath: /usr/local/run
            - name: hostetc
              mountPath: /usr/local/etc
            - name: hostmodules
              mountPath: /lib/modules
          livenessProbe:
            exec:
              command:
                - /usr/local/bin/liveness-ovs.sh
      restartPolicy: Always
      volumes:
        - name: hostetc
          hostPath:
            path: /etc
        - name: hostvar
          hostPath:
            path: /var
        - name: hostrun
          hostPath:
            path: /run
        - name: hostmodules
          hostPath:
            path: /lib/modules
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: aci-containers-controller
  namespace: kube-system
  labels:
    aci-containers-config-version: "6627d4d9-50a5-4674-896e-76403290b8f4"
    network-plugin: aci-containers
    name: aci-containers-controller
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      name: aci-containers-controller
      network-plugin: aci-containers
  template:
    metadata:
      name: aci-containers-controller
      namespace: kube-system
      labels:
        name: aci-containers-controller
        network-plugin: aci-containers
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      hostNetwork: true
      serviceAccountName: aci-containers-controller
      tolerations:
        - key: CriticalAddonsOnly
      containers:
        - name: aci-containers-controller
          image: noiro/aci-containers-controller:1.7r86
          imagePullPolicy: Always
          volumeMounts:
            - name: controller-config-volume
              mountPath: /usr/local/etc/aci-containers/
            - name: aci-user-cert-volume
              mountPath: /usr/local/etc/aci-cert/
          livenessProbe:
            httpGet:
              path: /status
              port: 8091
      volumes:
        - name: aci-user-cert-volume
          secret:
            secretName: aci-user-cert
        - name: controller-config-volume
          configMap:
            name: aci-containers-config
            items:
              - key: controller-config
                path: controller.conf
