apiVersion: v1
kind: ConfigMap
metadata:
  name: aci-containers-config
  namespace: kube-system
  labels:
    aci-containers-config-version: "1954619f-a2f1-46e8-a6ec-601cd80bab85"
    network-plugin: aci-containers
data:
  controller-config: |-
    {
        "log-level": "info",
        "apic-hosts": [
            "10.10.20.12"
        ],
        "apic-username": "kubesbx05",
        "apic-private-key-path": "/usr/local/etc/aci-cert/user.key",
        "aci-prefix": "kubesbx05",
        "aci-vmm-type": "Kubernetes",
        "aci-vmm-domain": "kubesbx05",
        "aci-vmm-controller": "kubesbx05",
        "aci-policy-tenant": "kubesbx05",
        "require-netpol-annot": false,
        "aci-service-phys-dom": "kubesbx05-pdom",
        "aci-service-encap": "vlan-913",
        "aci-service-monitor-interval": 15,
        "aci-vrf-tenant": "common",
        "aci-l3out": "sbx_shared_L3Out",
        "aci-ext-networks": [
            "any_ip"
        ],
        "aci-vrf": "sbx_shared",
        "default-endpoint-group": {
            "policy-space": "kubesbx05",
            "name": "kubernetes|kube-default"
        },
        "namespace-default-endpoint-group": {
            "kube-system": {
                "policy-space": "kubesbx05",
                "name": "kubernetes|kube-system"
            }
        },
        "service-ip-pool": [
            {
                "start": "172.20.5.194", 
                "end": "172.20.5.222"
            }
        ],
        "static-service-ip-pool": [
            {
                "start": "172.20.5.226", 
                "end": "172.20.5.254"
            }
        ],
        "pod-ip-pool": [
            {
                "start": "10.205.0.2", 
                "end": "10.205.255.254"
            }
        ],
        "node-service-ip-pool": [
            {
                "start": "192.168.105.2", 
                "end": "192.168.105.254"
            }
        ],
        "node-service-subnets": [
            "192.168.105.1/24"
        ]
    }
  host-agent-config: |-
    {
        "log-level": "info",
        "aci-vmm-type": "Kubernetes",
        "aci-vmm-domain": "kubesbx05",
        "aci-vmm-controller": "kubesbx05",
        "aci-vrf": "sbx_shared",
        "aci-vrf-tenant": "common",
        "service-vlan": 913,
        "encap-type": "vxlan",
        "aci-infra-vlan": 4093,
        "cni-netconfig": [
            {
                "routes": [
                    {
                        "gw": "10.205.0.1", 
                        "dst": "0.0.0.0/0"
                    }
                ], 
                "subnet": "10.205.0.0/16", 
                "gateway": "10.205.0.1"
            }
        ]
    }
  opflex-agent-config: |-
    {
        "log": {
            "level": "info"
        },
        "opflex": {
        }
    }
---
apiVersion: v1
kind: Secret
metadata:
  name: aci-user-cert
  namespace: kube-system
  labels:
    aci-containers-config-version: "1954619f-a2f1-46e8-a6ec-601cd80bab85"
data:
  user.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUNlQUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQW1Jd2dnSmVBZ0VBQW9HQkFPR2RHcmkrR2JIUU5IYkQKVHNDQTI2YWUxZ2wyeWJhaGNpalhPcWhscFRYNW5BZVVCY0JhUE5nM1pEL1ozVC9xYlJnR2RhSzZ0dy81WEUrNAp4Y2hMNjI4ZG9BaGFOakJlNCtKSTI0ZGFIbzFOdFFIamx4YTFrSzhUQlNYSzd2dHdvZ0Mrb1RCZ3pIdEc0ci9hCmtYb2xPNUZsYWZLbUlOanhlQWZZR1N5UXpJWlBBZ01CQUFFQ2dZRUFwSzhtK0Q5YlJoNHlqWlpXLzlHUGcvcGgKUmhzOWRtQTJrblU0emY4VUwyZjZhdFd6dFFxcGF6SlRyUC84cmxFU1BQMUtGUFN4OTZrUHB1bTdCVS9WazdGawpLdkQ5SWVPNnI3ZFVWaHhLYitLUmxiYlR6aGpCeEhrSDZWZzdtQlo0L2RlOW1DKzFpWEU2MHVibHNOcERJdEZ0CkplYmlRVm5hVlRSSVdYV3IvNUVDUVFEMDJhSE10bTFDcTJraFQ4VW0ycDdCanJGZS80SytRMGQzSnRwQ2xvQkUKejVVYXFjYy9Cc1dZdUl2QnJra1Z3NmlYaUVrYVJ6bGNSQTlLZ3BwcEVQcXJBa0VBNitNNHIySTZmQW9pRmxNcQpUWXhwQU4zTk5zT1ZPZGVpcHVFajFjNnhGSzAvZk5HVG91eWhLM0NINUE0cUtFbkpDUXZ6M2NTMWVDM0I5SEhCCk5GMWk3UUpCQU9XNEZleUpyMkxnalNiNnYzN2ZtQmtETm5ocGd4SGM3M3pqejl5dmRUS2FDMHRUeEtMbVNKY3IKZGJ2R043MmFyMTlVTnpuWFh3S292Q3ZzOHMvbVpUY0NRR2Q3ekc5c3FYbW5QR01NNHg4WVBTeUxJYThueUh5Uwp0Q0YvM2FlN3dJWHdwMHlMNkxmdUZacW9DSVd0RFNPVmt5TnI0ZlZsaWJNS1orOWtSRDFEeHRVQ1FRREc1di8yCmtiMTlZeFRyalY4ZS9iekFVdTdySFlPM0JiUDV4cFpFZDIxRDNJaXZjUUZ2Nzg3MWMycklJdWIrdW05QUNkamEKUVo5a284azNVS21ob3JVcAotLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tCg==
  user.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUI3RENDQVZVQ0FnUG9NQTBHQ1NxR1NJYjNEUUVCQlFVQU1ENHhDekFKQmdOVkJBWVRBbFZUTVJZd0ZBWUQKVlFRS0RBMURhWE5qYnlCVGVYTjBaVzF6TVJjd0ZRWURWUVFEREE1VmMyVnlJR3QxWW1WelluZ3dOVEFlRncweApPREExTXpFeE5EUXlNRE5hRncweU9EQTFNamt3TWpReU1ETmFNRDR4Q3pBSkJnTlZCQVlUQWxWVE1SWXdGQVlEClZRUUtEQTFEYVhOamJ5QlRlWE4wWlcxek1SY3dGUVlEVlFRRERBNVZjMlZ5SUd0MVltVnpZbmd3TlRDQm56QU4KQmdrcWhraUc5dzBCQVFFRkFBT0JqUUF3Z1lrQ2dZRUE0WjBhdUw0WnNkQTBkc05Pd0lEYnBwN1dDWGJKdHFGeQpLTmM2cUdXbE5mbWNCNVFGd0ZvODJEZGtQOW5kUCtwdEdBWjFvcnEzRC9sY1Q3akZ5RXZyYngyZ0NGbzJNRjdqCjRramJoMW9lalUyMUFlT1hGcldRcnhNRkpjcnUrM0NpQUw2aE1HRE1lMGJpdjlxUmVpVTdrV1ZwOHFZZzJQRjQKQjlnWkxKRE1oazhDQXdFQUFUQU5CZ2txaGtpRzl3MEJBUVVGQUFPQmdRQzl3eTFIY1V6UWRxdG9zVzJiTWErVAowaWx4K2JBMWJCUmJ6VnY3eWRkRi9UNWdGM3JEYjdCZUlaV2FDWUxyV3UvRFBTWFp4N2RQb1pNQ1A1VWk4YWFRCnExWGtaSjhoZnRzWk1EejFhbVE2RWJUa2FqUUxYaHQ5aWtLd2twb3lXbHR2dHlIRlJYYitTMExWYTFwYlE5WGoKL3BTVFVyU2prRnpvTVptQ0JjVmhEQT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aci-containers-controller
  namespace: kube-system
  labels:
    aci-containers-config-version: "1954619f-a2f1-46e8-a6ec-601cd80bab85"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aci-containers-host-agent
  namespace: kube-system
  labels:
    aci-containers-config-version: "1954619f-a2f1-46e8-a6ec-601cd80bab85"
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:
    aci-containers-config-version: "1954619f-a2f1-46e8-a6ec-601cd80bab85"
    network-plugin: aci-containers
  name: aci-containers:controller
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - namespaces
  - pods
  - endpoints
  - services
  verbs:
  - list
  - watch
  - get
- apiGroups:
  - "networking.k8s.io"
  resources:
  - networkpolicies
  verbs:
  - list
  - watch
  - get
- apiGroups:
  - "extensions"
  resources:
  - deployments
  - replicasets
  verbs:
  - list
  - watch
  - get
- apiGroups:
  - ""
  resources:
  - pods
  - nodes
  - services/status
  verbs:
  - update
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:
    aci-containers-config-version: "1954619f-a2f1-46e8-a6ec-601cd80bab85"
    network-plugin: aci-containers
  name: aci-containers:host-agent
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - pods
  - endpoints
  - services
  verbs:
  - list
  - watch
  - get
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: aci-containers:controller
  labels:
    aci-containers-config-version: "1954619f-a2f1-46e8-a6ec-601cd80bab85"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: aci-containers:controller
subjects:
- kind: ServiceAccount
  name: aci-containers-controller
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: aci-containers:host-agent
  labels:
    aci-containers-config-version: "1954619f-a2f1-46e8-a6ec-601cd80bab85"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: aci-containers:host-agent
subjects:
- kind: ServiceAccount
  name: aci-containers-host-agent
  namespace: kube-system
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: aci-containers-host
  namespace: kube-system
  labels:
    aci-containers-config-version: "1954619f-a2f1-46e8-a6ec-601cd80bab85"
    network-plugin: aci-containers
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      name: aci-containers-host
      network-plugin: aci-containers
  template:
    metadata:
      labels:
        name: aci-containers-host
        network-plugin: aci-containers
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      hostNetwork: true
      hostPID: true
      hostIPC: true
      serviceAccountName: aci-containers-host-agent
      tolerations:
        - key: CriticalAddonsOnly
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
      containers:
        - name: aci-containers-host
          image: noiro/aci-containers-host:1.7r86
          imagePullPolicy: Always
          securityContext:
            capabilities:
              add:
                - SYS_ADMIN
                - NET_ADMIN
          env:
            - name: KUBERNETES_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: cni-bin
              mountPath: /mnt/cni-bin
            - name: cni-conf
              mountPath: /mnt/cni-conf
            - name: hostvar
              mountPath: /usr/local/var
            - name: hostrun
              mountPath: /run
            - name: hostrun
              mountPath: /usr/local/run
            - name: opflex-hostconfig-volume
              mountPath: /usr/local/etc/opflex-agent-ovs/base-conf.d
            - name: host-config-volume
              mountPath: /usr/local/etc/aci-containers/
          livenessProbe:
            httpGet:
              path: /status
              port: 8090
        - name: opflex-agent
          image: noiro/opflex:1.7r70
          imagePullPolicy: Always
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          volumeMounts:
            - name: hostvar
              mountPath: /usr/local/var
            - name: hostrun
              mountPath: /run
            - name: hostrun
              mountPath: /usr/local/run
            - name: opflex-hostconfig-volume
              mountPath: /usr/local/etc/opflex-agent-ovs/base-conf.d
            - name: opflex-config-volume
              mountPath: /usr/local/etc/opflex-agent-ovs/conf.d
        - name: mcast-daemon
          image: noiro/opflex:1.7r70
          command: ["/bin/sh"]
          args: ["/usr/local/bin/launch-mcastdaemon.sh"]
          imagePullPolicy: Always
          volumeMounts:
            - name: hostvar
              mountPath: /usr/local/var
            - name: hostrun
              mountPath: /run
            - name: hostrun
              mountPath: /usr/local/run
      restartPolicy: Always
      volumes:
        - name: cni-bin
          hostPath:
            path: /opt
        - name: cni-conf
          hostPath:
            path: /etc
        - name: hostvar
          hostPath:
            path: /var
        - name: hostrun
          hostPath:
            path: /run
        - name: host-config-volume
          configMap:
            name: aci-containers-config
            items:
              - key: host-agent-config
                path: host-agent.conf
        - name: opflex-hostconfig-volume
          emptyDir:
            medium: Memory
        - name: opflex-config-volume
          configMap:
            name: aci-containers-config
            items:
              - key: opflex-agent-config
                path: local.conf
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: aci-containers-openvswitch
  namespace: kube-system
  labels:
    aci-containers-config-version: "1954619f-a2f1-46e8-a6ec-601cd80bab85"
    network-plugin: aci-containers
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      name: aci-containers-openvswitch
      network-plugin: aci-containers
  template:
    metadata:
      labels:
        name: aci-containers-openvswitch
        network-plugin: aci-containers
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      hostNetwork: true
      hostPID: true
      hostIPC: true
      serviceAccountName: aci-containers-host-agent
      tolerations:
        - key: CriticalAddonsOnly
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
      containers:
        - name: aci-containers-openvswitch
          image: noiro/openvswitch:1.7r24
          imagePullPolicy: Always
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - SYS_MODULE
                - SYS_NICE
                - IPC_LOCK
          env:
            - name: OVS_RUNDIR
              value: /usr/local/var/run/openvswitch
          volumeMounts:
            - name: hostvar
              mountPath: /usr/local/var
            - name: hostrun
              mountPath: /run
            - name: hostrun
              mountPath: /usr/local/run
            - name: hostetc
              mountPath: /usr/local/etc
            - name: hostmodules
              mountPath: /lib/modules
          livenessProbe:
            exec:
              command:
                - /usr/local/bin/liveness-ovs.sh
      restartPolicy: Always
      volumes:
        - name: hostetc
          hostPath:
            path: /etc
        - name: hostvar
          hostPath:
            path: /var
        - name: hostrun
          hostPath:
            path: /run
        - name: hostmodules
          hostPath:
            path: /lib/modules
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: aci-containers-controller
  namespace: kube-system
  labels:
    aci-containers-config-version: "1954619f-a2f1-46e8-a6ec-601cd80bab85"
    network-plugin: aci-containers
    name: aci-containers-controller
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      name: aci-containers-controller
      network-plugin: aci-containers
  template:
    metadata:
      name: aci-containers-controller
      namespace: kube-system
      labels:
        name: aci-containers-controller
        network-plugin: aci-containers
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      hostNetwork: true
      serviceAccountName: aci-containers-controller
      tolerations:
        - key: CriticalAddonsOnly
      containers:
        - name: aci-containers-controller
          image: noiro/aci-containers-controller:1.7r86
          imagePullPolicy: Always
          volumeMounts:
            - name: controller-config-volume
              mountPath: /usr/local/etc/aci-containers/
            - name: aci-user-cert-volume
              mountPath: /usr/local/etc/aci-cert/
          livenessProbe:
            httpGet:
              path: /status
              port: 8091
      volumes:
        - name: aci-user-cert-volume
          secret:
            secretName: aci-user-cert
        - name: controller-config-volume
          configMap:
            name: aci-containers-config
            items:
              - key: controller-config
                path: controller.conf
