apiVersion: v1
kind: ConfigMap
metadata:
  name: aci-containers-config
  namespace: kube-system
  labels:
    aci-containers-config-version: "b98363a6-1a5a-4272-adcc-8305ece920b5"
    network-plugin: aci-containers
data:
  controller-config: |-
    {
        "log-level": "info",
        "apic-hosts": [
            "10.10.20.12"
        ],
        "apic-username": "kubesbx06",
        "apic-private-key-path": "/usr/local/etc/aci-cert/user.key",
        "aci-prefix": "kubesbx06",
        "aci-vmm-type": "Kubernetes",
        "aci-vmm-domain": "kubesbx06",
        "aci-vmm-controller": "kubesbx06",
        "aci-policy-tenant": "kubesbx06",
        "require-netpol-annot": false,
        "aci-service-phys-dom": "kubesbx06-pdom",
        "aci-service-encap": "vlan-915",
        "aci-service-monitor-interval": 15,
        "aci-vrf-tenant": "common",
        "aci-l3out": "sbx_shared_L3Out",
        "aci-ext-networks": [
            "any_ip"
        ],
        "aci-vrf": "sbx_shared",
        "default-endpoint-group": {
            "policy-space": "kubesbx06",
            "name": "kubernetes|kube-default"
        },
        "namespace-default-endpoint-group": {
            "kube-system": {
                "policy-space": "kubesbx06",
                "name": "kubernetes|kube-system"
            }
        },
        "service-ip-pool": [
            {
                "start": "172.20.6.194", 
                "end": "172.20.6.222"
            }
        ],
        "static-service-ip-pool": [
            {
                "start": "172.20.6.226", 
                "end": "172.20.6.254"
            }
        ],
        "pod-ip-pool": [
            {
                "start": "10.206.0.2", 
                "end": "10.206.255.254"
            }
        ],
        "node-service-ip-pool": [
            {
                "start": "192.168.106.2", 
                "end": "192.168.106.254"
            }
        ],
        "node-service-subnets": [
            "192.168.106.1/24"
        ]
    }
  host-agent-config: |-
    {
        "log-level": "info",
        "aci-vmm-type": "Kubernetes",
        "aci-vmm-domain": "kubesbx06",
        "aci-vmm-controller": "kubesbx06",
        "aci-vrf": "sbx_shared",
        "aci-vrf-tenant": "common",
        "service-vlan": 915,
        "encap-type": "vxlan",
        "aci-infra-vlan": 4093,
        "cni-netconfig": [
            {
                "routes": [
                    {
                        "gw": "10.206.0.1", 
                        "dst": "0.0.0.0/0"
                    }
                ], 
                "subnet": "10.206.0.0/16", 
                "gateway": "10.206.0.1"
            }
        ]
    }
  opflex-agent-config: |-
    {
        "log": {
            "level": "info"
        },
        "opflex": {
        }
    }
---
apiVersion: v1
kind: Secret
metadata:
  name: aci-user-cert
  namespace: kube-system
  labels:
    aci-containers-config-version: "b98363a6-1a5a-4272-adcc-8305ece920b5"
data:
  user.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUNkZ0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQW1Bd2dnSmNBZ0VBQW9HQkFOaEN0VHJZT05yWnQwbVkKWHYxUUdyK0FvS0g2NksxQTZ0bFZWUFZlUVpKaW5WSWpiZys3SUkwRkthV0NmQ1czb3N3Y0o2UldWRWRLcTJOSwp4cHptREVIbVJLdkpUYWZmMG5yZ09yTTZ3Q0czcjVaSFdvdURlUG8xQW14WnM3OThqdHpGNEtFQVZRVWNxdzB2Cnk5SkpoTld2QU9jdHByTUMyc1JoYldFREVDdmpBZ01CQUFFQ2dZQWs1dVVqNEdkN09MRms5b0ltK1hkRy9EenMKeHZMVE5ZT2RpRWtTQVg1dzZ6RHJKaTZPc3FDd1Q1UTJzTmhjVzBTRlRieVo5ejAwV1JKN3cvTzJMQzhrOHhOWgpzbHpydWZnekVEQUZRYS96T0ZEMkFKLzNZVEU5SGNSUE1jWVNwNmRoaENhNVYzaC9hY0NvbEJQSi93eTkvRDNOCm5tMEhyNXlPYkJQamwvZmphUUpCQVB6RWVLWlE2QVZzM1IxTkFheURFSWllRGJYc0lvczBBdEIzVW9lZlRJa0wKM2trcEZ3alhRK3h6bXp4NzNQOGFvMkR1dkV2NEE4Y3ZFSmVKMFdjWUljY0NRUURiQnJlN3FYMVU4Rno5emZTTApRZ09PblhiYjk4NmJMVVFtTFJXeXZCbHpQMlAwYWNPTzdMeTMvSnI2ajRiNmRaNW1uYXlEV2xrbEdBRElUVi96Cm5HVUZBa0JET3FKNFlmYUVVdU13d3VXYUU3WVhFQ3JIWTBvQXlsR2hUc3RWcFNuL0hYZis3MzNmN1JsMHozN1AKaElaUUY2Nnl2bXk0cS91ZFE4aGU5ZG9MV0tETEFrRUFycUY3aXQvSE14cjJPZEtsWVFjQVNReFpnV2JpVHkxWApRY3orbU9TS3NpM2ZwemRRbWJzOWVNQ3FYSTVsUTNyV0VlRXpkQU5zUWp3U0c2STlsOEdoZFFKQU8rNS9SN1E4CmdmVmpuc3lzMjVobHZGTXAyUTFZVTk2bU1GaEdGUk41MG9FWDhrL0tDNk9KbnZ2d2hZSExpaEV5c0JtcXplUE8KN0FBZ0twZXp0VTBnM1E9PQotLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tCg==
  user.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUI3RENDQVZVQ0FnUG9NQTBHQ1NxR1NJYjNEUUVCQlFVQU1ENHhDekFKQmdOVkJBWVRBbFZUTVJZd0ZBWUQKVlFRS0RBMURhWE5qYnlCVGVYTjBaVzF6TVJjd0ZRWURWUVFEREE1VmMyVnlJR3QxWW1WelluZ3dOakFlRncweApPREExTXpFeE5EVTBNekJhRncweU9EQTFNamt3TWpVME16QmFNRDR4Q3pBSkJnTlZCQVlUQWxWVE1SWXdGQVlEClZRUUtEQTFEYVhOamJ5QlRlWE4wWlcxek1SY3dGUVlEVlFRRERBNVZjMlZ5SUd0MVltVnpZbmd3TmpDQm56QU4KQmdrcWhraUc5dzBCQVFFRkFBT0JqUUF3Z1lrQ2dZRUEyRUsxT3RnNDJ0bTNTWmhlL1ZBYXY0Q2dvZnJvclVEcQoyVlZVOVY1QmttS2RVaU51RDdzZ2pRVXBwWUo4SmJlaXpCd25wRlpVUjBxclkwckduT1lNUWVaRXE4bE5wOS9TCmV1QTZzenJBSWJldmxrZGFpNE40K2pVQ2JGbXp2M3lPM01YZ29RQlZCUnlyRFMvTDBrbUUxYThBNXkybXN3TGEKeEdGdFlRTVFLK01DQXdFQUFUQU5CZ2txaGtpRzl3MEJBUVVGQUFPQmdRQ2g0WDdCZ3RQQWlYOGF5dGhTaHNPKwpuVVFIbVBUMjJoNFk0aWxIV3FENUNjK3J2WUI4VjdwRGVhVFJ4c2ZZRnB0QUNnQ2NRNDhJTEhBc0NhT1FndGRYCkllcVorQThNWVFMZlhrZ2dhNjVSTUF1SHhsenlCbFd0ZVduUFp1SUczOTNxUFZtTTNVaFhFY00xVnhZYU9hS08KWlpjL3QrTjJMYk92RDFJQTFwM29EQT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aci-containers-controller
  namespace: kube-system
  labels:
    aci-containers-config-version: "b98363a6-1a5a-4272-adcc-8305ece920b5"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aci-containers-host-agent
  namespace: kube-system
  labels:
    aci-containers-config-version: "b98363a6-1a5a-4272-adcc-8305ece920b5"
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:
    aci-containers-config-version: "b98363a6-1a5a-4272-adcc-8305ece920b5"
    network-plugin: aci-containers
  name: aci-containers:controller
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - namespaces
  - pods
  - endpoints
  - services
  verbs:
  - list
  - watch
  - get
- apiGroups:
  - "networking.k8s.io"
  resources:
  - networkpolicies
  verbs:
  - list
  - watch
  - get
- apiGroups:
  - "extensions"
  resources:
  - deployments
  - replicasets
  verbs:
  - list
  - watch
  - get
- apiGroups:
  - ""
  resources:
  - pods
  - nodes
  - services/status
  verbs:
  - update
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:
    aci-containers-config-version: "b98363a6-1a5a-4272-adcc-8305ece920b5"
    network-plugin: aci-containers
  name: aci-containers:host-agent
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - pods
  - endpoints
  - services
  verbs:
  - list
  - watch
  - get
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: aci-containers:controller
  labels:
    aci-containers-config-version: "b98363a6-1a5a-4272-adcc-8305ece920b5"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: aci-containers:controller
subjects:
- kind: ServiceAccount
  name: aci-containers-controller
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: aci-containers:host-agent
  labels:
    aci-containers-config-version: "b98363a6-1a5a-4272-adcc-8305ece920b5"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: aci-containers:host-agent
subjects:
- kind: ServiceAccount
  name: aci-containers-host-agent
  namespace: kube-system
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: aci-containers-host
  namespace: kube-system
  labels:
    aci-containers-config-version: "b98363a6-1a5a-4272-adcc-8305ece920b5"
    network-plugin: aci-containers
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      name: aci-containers-host
      network-plugin: aci-containers
  template:
    metadata:
      labels:
        name: aci-containers-host
        network-plugin: aci-containers
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      hostNetwork: true
      hostPID: true
      hostIPC: true
      serviceAccountName: aci-containers-host-agent
      tolerations:
        - key: CriticalAddonsOnly
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
      containers:
        - name: aci-containers-host
          image: noiro/aci-containers-host:1.7r86
          imagePullPolicy: Always
          securityContext:
            capabilities:
              add:
                - SYS_ADMIN
                - NET_ADMIN
          env:
            - name: KUBERNETES_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: cni-bin
              mountPath: /mnt/cni-bin
            - name: cni-conf
              mountPath: /mnt/cni-conf
            - name: hostvar
              mountPath: /usr/local/var
            - name: hostrun
              mountPath: /run
            - name: hostrun
              mountPath: /usr/local/run
            - name: opflex-hostconfig-volume
              mountPath: /usr/local/etc/opflex-agent-ovs/base-conf.d
            - name: host-config-volume
              mountPath: /usr/local/etc/aci-containers/
          livenessProbe:
            httpGet:
              path: /status
              port: 8090
        - name: opflex-agent
          image: noiro/opflex:1.7r70
          imagePullPolicy: Always
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          volumeMounts:
            - name: hostvar
              mountPath: /usr/local/var
            - name: hostrun
              mountPath: /run
            - name: hostrun
              mountPath: /usr/local/run
            - name: opflex-hostconfig-volume
              mountPath: /usr/local/etc/opflex-agent-ovs/base-conf.d
            - name: opflex-config-volume
              mountPath: /usr/local/etc/opflex-agent-ovs/conf.d
        - name: mcast-daemon
          image: noiro/opflex:1.7r70
          command: ["/bin/sh"]
          args: ["/usr/local/bin/launch-mcastdaemon.sh"]
          imagePullPolicy: Always
          volumeMounts:
            - name: hostvar
              mountPath: /usr/local/var
            - name: hostrun
              mountPath: /run
            - name: hostrun
              mountPath: /usr/local/run
      restartPolicy: Always
      volumes:
        - name: cni-bin
          hostPath:
            path: /opt
        - name: cni-conf
          hostPath:
            path: /etc
        - name: hostvar
          hostPath:
            path: /var
        - name: hostrun
          hostPath:
            path: /run
        - name: host-config-volume
          configMap:
            name: aci-containers-config
            items:
              - key: host-agent-config
                path: host-agent.conf
        - name: opflex-hostconfig-volume
          emptyDir:
            medium: Memory
        - name: opflex-config-volume
          configMap:
            name: aci-containers-config
            items:
              - key: opflex-agent-config
                path: local.conf
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: aci-containers-openvswitch
  namespace: kube-system
  labels:
    aci-containers-config-version: "b98363a6-1a5a-4272-adcc-8305ece920b5"
    network-plugin: aci-containers
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      name: aci-containers-openvswitch
      network-plugin: aci-containers
  template:
    metadata:
      labels:
        name: aci-containers-openvswitch
        network-plugin: aci-containers
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      hostNetwork: true
      hostPID: true
      hostIPC: true
      serviceAccountName: aci-containers-host-agent
      tolerations:
        - key: CriticalAddonsOnly
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
      containers:
        - name: aci-containers-openvswitch
          image: noiro/openvswitch:1.7r24
          imagePullPolicy: Always
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - SYS_MODULE
                - SYS_NICE
                - IPC_LOCK
          env:
            - name: OVS_RUNDIR
              value: /usr/local/var/run/openvswitch
          volumeMounts:
            - name: hostvar
              mountPath: /usr/local/var
            - name: hostrun
              mountPath: /run
            - name: hostrun
              mountPath: /usr/local/run
            - name: hostetc
              mountPath: /usr/local/etc
            - name: hostmodules
              mountPath: /lib/modules
          livenessProbe:
            exec:
              command:
                - /usr/local/bin/liveness-ovs.sh
      restartPolicy: Always
      volumes:
        - name: hostetc
          hostPath:
            path: /etc
        - name: hostvar
          hostPath:
            path: /var
        - name: hostrun
          hostPath:
            path: /run
        - name: hostmodules
          hostPath:
            path: /lib/modules
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: aci-containers-controller
  namespace: kube-system
  labels:
    aci-containers-config-version: "b98363a6-1a5a-4272-adcc-8305ece920b5"
    network-plugin: aci-containers
    name: aci-containers-controller
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      name: aci-containers-controller
      network-plugin: aci-containers
  template:
    metadata:
      name: aci-containers-controller
      namespace: kube-system
      labels:
        name: aci-containers-controller
        network-plugin: aci-containers
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      hostNetwork: true
      serviceAccountName: aci-containers-controller
      tolerations:
        - key: CriticalAddonsOnly
      containers:
        - name: aci-containers-controller
          image: noiro/aci-containers-controller:1.7r86
          imagePullPolicy: Always
          volumeMounts:
            - name: controller-config-volume
              mountPath: /usr/local/etc/aci-containers/
            - name: aci-user-cert-volume
              mountPath: /usr/local/etc/aci-cert/
          livenessProbe:
            httpGet:
              path: /status
              port: 8091
      volumes:
        - name: aci-user-cert-volume
          secret:
            secretName: aci-user-cert
        - name: controller-config-volume
          configMap:
            name: aci-containers-config
            items:
              - key: controller-config
                path: controller.conf
