apiVersion: v1
kind: ConfigMap
metadata:
  name: aci-containers-config
  namespace: kube-system
  labels:
    aci-containers-config-version: "48a1d862-dfbf-4091-b292-891fcc783418"
    network-plugin: aci-containers
data:
  controller-config: |-
    {
        "log-level": "info",
        "apic-hosts": [
            "10.10.20.12"
        ],
        "apic-username": "kubesbx11",
        "apic-private-key-path": "/usr/local/etc/aci-cert/user.key",
        "aci-prefix": "kubesbx11",
        "aci-vmm-type": "Kubernetes",
        "aci-vmm-domain": "kubesbx11",
        "aci-vmm-controller": "kubesbx11",
        "aci-policy-tenant": "kubesbx11",
        "require-netpol-annot": false,
        "aci-service-phys-dom": "kubesbx11-pdom",
        "aci-service-encap": "vlan-925",
        "aci-service-monitor-interval": 15,
        "aci-vrf-tenant": "common",
        "aci-l3out": "sbx_shared_L3Out",
        "aci-ext-networks": [
            "any_ip"
        ],
        "aci-vrf": "sbx_shared",
        "default-endpoint-group": {
            "policy-space": "kubesbx11",
            "name": "kubernetes|kube-default"
        },
        "namespace-default-endpoint-group": {
            "kube-system": {
                "policy-space": "kubesbx11",
                "name": "kubernetes|kube-system"
            }
        },
        "service-ip-pool": [
            {
                "start": "172.20.11.194", 
                "end": "172.20.11.222"
            }
        ],
        "static-service-ip-pool": [
            {
                "start": "172.20.11.226", 
                "end": "172.20.11.254"
            }
        ],
        "pod-ip-pool": [
            {
                "start": "10.211.0.2", 
                "end": "10.211.255.254"
            }
        ],
        "node-service-ip-pool": [
            {
                "start": "192.168.111.2", 
                "end": "192.168.111.254"
            }
        ],
        "node-service-subnets": [
            "192.168.111.1/24"
        ]
    }
  host-agent-config: |-
    {
        "log-level": "info",
        "aci-vmm-type": "Kubernetes",
        "aci-vmm-domain": "kubesbx11",
        "aci-vmm-controller": "kubesbx11",
        "aci-vrf": "sbx_shared",
        "aci-vrf-tenant": "common",
        "service-vlan": 925,
        "encap-type": "vxlan",
        "aci-infra-vlan": 4093,
        "cni-netconfig": [
            {
                "routes": [
                    {
                        "gw": "10.211.0.1", 
                        "dst": "0.0.0.0/0"
                    }
                ], 
                "subnet": "10.211.0.0/16", 
                "gateway": "10.211.0.1"
            }
        ]
    }
  opflex-agent-config: |-
    {
        "log": {
            "level": "info"
        },
        "opflex": {
        }
    }
---
apiVersion: v1
kind: Secret
metadata:
  name: aci-user-cert
  namespace: kube-system
  labels:
    aci-containers-config-version: "48a1d862-dfbf-4091-b292-891fcc783418"
data:
  user.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUNkd0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQW1Fd2dnSmRBZ0VBQW9HQkFONjNYM1VnMG1pSExQaXoKMjBpUmk3SGpYN3gvY2hOQnlQNFFMQm50WTRvT0kzMHZ1dU1IWm1xdWtDeGRSVGJsZHVwOEx4Tlk3TU1HRDJJdgo0cjRiamhNdWY5dExRQVIvc1Z5dk1UazNDM1hYZ0JPSlhhQnMwNy9yZnlzdHE5VTA4Y0Z2MVBSVkZhclY3SW9iCjNzZ1BuUzUxTm9WUkF4WWt2Q1JDZTc5eU9wRW5BZ01CQUFFQ2dZQWczWUI1b1ZGTFdYODZhQmdZMmxsNTg2cWgKLzFDUEpPc0xDc25uUFkrdHhLNVovOXdkT205VG1OVHZwd2ZhdFB2YVdGNytCT1pUVlNhWi82VC9Gc1BkTEMrSQpFT2VMYkhCT1RLYjRKZm56TXMxbE1yV2hCa0NiQjVJK1ovUlIrbTBPVmpHTTROaG8rT1k1WjJxWHN1dkxXWlJFCmxBM0dRVnlJcXVOdlBwRXNtUUpCQVB4NHdlYndqcEdCVlZaRDJVRHdVT0FZU2svM0c0dVRiNFFYQUtEeVJqaEQKRnZxRExuRE1Fa08xcFY3aTd0M2pJaEI2TEgweFVyUjBrY2grSDB6bkp5VUNRUURoMUNtYllWSGdwRVR5UFZKOQpOZnN6c0wxamtydUUyZVFIQk9hbGlRb0h6SldRN25xU1UzS3U0SkJieUdMTmhYaFUrQjAwMmpNUUVEOUxOc1hRClY5dGJBa0JjZHRWOUFPa1YvU29GMS85L093UkRybUc0KzZWSTd3eE9jaVkyeThSUDRySk51VEdPK2c1T1lmNVkKeS8vem43WGdGdjZvTXlJNUdPQXpiNDJER3IxSkFrRUFnS0FuVXFrTHliZkd6WExBR1RFMTh5c250QjlQVDB3TAo1VE9WYTVPeWN0N0VFZGpEVjdUUURXczZ6Z3hFdW1yYkx3cGpHRWR2N2laUzVyUTcxMzh6SVFKQkFPVTl3TFZMCm5IaGJpUkxNbytnckFzY0h2MzZhdXdBMkxBU0dQTUh1dmE0Y3FyQzY3WlhWRXlWRjFIckdMN2dVaEdhd2dyQ0kKQ1NNZ0dySHRmbXY2UkNBPQotLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tCg==
  user.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUI3RENDQVZVQ0FnUG9NQTBHQ1NxR1NJYjNEUUVCQlFVQU1ENHhDekFKQmdOVkJBWVRBbFZUTVJZd0ZBWUQKVlFRS0RBMURhWE5qYnlCVGVYTjBaVzF6TVJjd0ZRWURWUVFEREE1VmMyVnlJR3QxWW1WelluZ3hNVEFlRncweApPREExTXpFeE5EUXlNelphRncweU9EQTFNamt3TWpReU16WmFNRDR4Q3pBSkJnTlZCQVlUQWxWVE1SWXdGQVlEClZRUUtEQTFEYVhOamJ5QlRlWE4wWlcxek1SY3dGUVlEVlFRRERBNVZjMlZ5SUd0MVltVnpZbmd4TVRDQm56QU4KQmdrcWhraUc5dzBCQVFFRkFBT0JqUUF3Z1lrQ2dZRUEzcmRmZFNEU2FJY3MrTFBiU0pHTHNlTmZ2SDl5RTBISQovaEFzR2UxamlnNGpmUys2NHdkbWFxNlFMRjFGTnVWMjZud3ZFMWpzd3dZUFlpL2l2aHVPRXk1LzIwdEFCSCt4ClhLOHhPVGNMZGRlQUU0bGRvR3pUdit0L0t5MnIxVFR4d1cvVTlGVVZxdFhzaWh2ZXlBK2RMblUyaFZFREZpUzgKSkVKN3YzSTZrU2NDQXdFQUFUQU5CZ2txaGtpRzl3MEJBUVVGQUFPQmdRQlpSbUptNlo1OHZqMmNLSUlCbjRiVAo2SHRpZFlUMDh2VExqdjA2anF6bHByRFpFNmlsa21IWndSeUI2UEpVZnFGbkpoNXA2bkszdm5QVDZjcFZ4TEhJClFLbU1Sb1pacjRNM2ZSa3N1Y1dPaXMyYVlaN2hObnNBNzByWTFuYi8rWWNvQUxSSEw4Slo5T0UwMFBtbUVqQW0KWWpGejlOVlpSejRXSHZhcEJTbk5XQT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aci-containers-controller
  namespace: kube-system
  labels:
    aci-containers-config-version: "48a1d862-dfbf-4091-b292-891fcc783418"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aci-containers-host-agent
  namespace: kube-system
  labels:
    aci-containers-config-version: "48a1d862-dfbf-4091-b292-891fcc783418"
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:
    aci-containers-config-version: "48a1d862-dfbf-4091-b292-891fcc783418"
    network-plugin: aci-containers
  name: aci-containers:controller
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - namespaces
  - pods
  - endpoints
  - services
  verbs:
  - list
  - watch
  - get
- apiGroups:
  - "networking.k8s.io"
  resources:
  - networkpolicies
  verbs:
  - list
  - watch
  - get
- apiGroups:
  - "extensions"
  resources:
  - deployments
  - replicasets
  verbs:
  - list
  - watch
  - get
- apiGroups:
  - ""
  resources:
  - pods
  - nodes
  - services/status
  verbs:
  - update
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:
    aci-containers-config-version: "48a1d862-dfbf-4091-b292-891fcc783418"
    network-plugin: aci-containers
  name: aci-containers:host-agent
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - pods
  - endpoints
  - services
  verbs:
  - list
  - watch
  - get
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: aci-containers:controller
  labels:
    aci-containers-config-version: "48a1d862-dfbf-4091-b292-891fcc783418"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: aci-containers:controller
subjects:
- kind: ServiceAccount
  name: aci-containers-controller
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: aci-containers:host-agent
  labels:
    aci-containers-config-version: "48a1d862-dfbf-4091-b292-891fcc783418"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: aci-containers:host-agent
subjects:
- kind: ServiceAccount
  name: aci-containers-host-agent
  namespace: kube-system
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: aci-containers-host
  namespace: kube-system
  labels:
    aci-containers-config-version: "48a1d862-dfbf-4091-b292-891fcc783418"
    network-plugin: aci-containers
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      name: aci-containers-host
      network-plugin: aci-containers
  template:
    metadata:
      labels:
        name: aci-containers-host
        network-plugin: aci-containers
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      hostNetwork: true
      hostPID: true
      hostIPC: true
      serviceAccountName: aci-containers-host-agent
      tolerations:
        - key: CriticalAddonsOnly
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
      containers:
        - name: aci-containers-host
          image: noiro/aci-containers-host:1.7r86
          imagePullPolicy: Always
          securityContext:
            capabilities:
              add:
                - SYS_ADMIN
                - NET_ADMIN
          env:
            - name: KUBERNETES_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: cni-bin
              mountPath: /mnt/cni-bin
            - name: cni-conf
              mountPath: /mnt/cni-conf
            - name: hostvar
              mountPath: /usr/local/var
            - name: hostrun
              mountPath: /run
            - name: hostrun
              mountPath: /usr/local/run
            - name: opflex-hostconfig-volume
              mountPath: /usr/local/etc/opflex-agent-ovs/base-conf.d
            - name: host-config-volume
              mountPath: /usr/local/etc/aci-containers/
          livenessProbe:
            httpGet:
              path: /status
              port: 8090
        - name: opflex-agent
          image: noiro/opflex:1.7r70
          imagePullPolicy: Always
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          volumeMounts:
            - name: hostvar
              mountPath: /usr/local/var
            - name: hostrun
              mountPath: /run
            - name: hostrun
              mountPath: /usr/local/run
            - name: opflex-hostconfig-volume
              mountPath: /usr/local/etc/opflex-agent-ovs/base-conf.d
            - name: opflex-config-volume
              mountPath: /usr/local/etc/opflex-agent-ovs/conf.d
        - name: mcast-daemon
          image: noiro/opflex:1.7r70
          command: ["/bin/sh"]
          args: ["/usr/local/bin/launch-mcastdaemon.sh"]
          imagePullPolicy: Always
          volumeMounts:
            - name: hostvar
              mountPath: /usr/local/var
            - name: hostrun
              mountPath: /run
            - name: hostrun
              mountPath: /usr/local/run
      restartPolicy: Always
      volumes:
        - name: cni-bin
          hostPath:
            path: /opt
        - name: cni-conf
          hostPath:
            path: /etc
        - name: hostvar
          hostPath:
            path: /var
        - name: hostrun
          hostPath:
            path: /run
        - name: host-config-volume
          configMap:
            name: aci-containers-config
            items:
              - key: host-agent-config
                path: host-agent.conf
        - name: opflex-hostconfig-volume
          emptyDir:
            medium: Memory
        - name: opflex-config-volume
          configMap:
            name: aci-containers-config
            items:
              - key: opflex-agent-config
                path: local.conf
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: aci-containers-openvswitch
  namespace: kube-system
  labels:
    aci-containers-config-version: "48a1d862-dfbf-4091-b292-891fcc783418"
    network-plugin: aci-containers
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      name: aci-containers-openvswitch
      network-plugin: aci-containers
  template:
    metadata:
      labels:
        name: aci-containers-openvswitch
        network-plugin: aci-containers
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      hostNetwork: true
      hostPID: true
      hostIPC: true
      serviceAccountName: aci-containers-host-agent
      tolerations:
        - key: CriticalAddonsOnly
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
      containers:
        - name: aci-containers-openvswitch
          image: noiro/openvswitch:1.7r24
          imagePullPolicy: Always
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - SYS_MODULE
                - SYS_NICE
                - IPC_LOCK
          env:
            - name: OVS_RUNDIR
              value: /usr/local/var/run/openvswitch
          volumeMounts:
            - name: hostvar
              mountPath: /usr/local/var
            - name: hostrun
              mountPath: /run
            - name: hostrun
              mountPath: /usr/local/run
            - name: hostetc
              mountPath: /usr/local/etc
            - name: hostmodules
              mountPath: /lib/modules
          livenessProbe:
            exec:
              command:
                - /usr/local/bin/liveness-ovs.sh
      restartPolicy: Always
      volumes:
        - name: hostetc
          hostPath:
            path: /etc
        - name: hostvar
          hostPath:
            path: /var
        - name: hostrun
          hostPath:
            path: /run
        - name: hostmodules
          hostPath:
            path: /lib/modules
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: aci-containers-controller
  namespace: kube-system
  labels:
    aci-containers-config-version: "48a1d862-dfbf-4091-b292-891fcc783418"
    network-plugin: aci-containers
    name: aci-containers-controller
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      name: aci-containers-controller
      network-plugin: aci-containers
  template:
    metadata:
      name: aci-containers-controller
      namespace: kube-system
      labels:
        name: aci-containers-controller
        network-plugin: aci-containers
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      hostNetwork: true
      serviceAccountName: aci-containers-controller
      tolerations:
        - key: CriticalAddonsOnly
      containers:
        - name: aci-containers-controller
          image: noiro/aci-containers-controller:1.7r86
          imagePullPolicy: Always
          volumeMounts:
            - name: controller-config-volume
              mountPath: /usr/local/etc/aci-containers/
            - name: aci-user-cert-volume
              mountPath: /usr/local/etc/aci-cert/
          livenessProbe:
            httpGet:
              path: /status
              port: 8091
      volumes:
        - name: aci-user-cert-volume
          secret:
            secretName: aci-user-cert
        - name: controller-config-volume
          configMap:
            name: aci-containers-config
            items:
              - key: controller-config
                path: controller.conf
