apiVersion: v1
kind: Namespace
metadata: 
   name: challenge
   labels:
      name: challenge
---
apiVersion: v1
kind: Pod
metadata:
   name: hello-cisco
   namespace: challenge
spec:
   containers:
   - name: hello-cisco
     image: mimaurer/hello-cisco:v1
     ports:
     - containerPort: 5000
