apiVersion: v1
kind: ConfigMap
metadata:
  name: aci-containers-config
  namespace: kube-system
  labels:
    aci-containers-config-version: "a7d695b6-5fd3-4ad5-a0ac-aeb052561ff3"
    network-plugin: aci-containers
data:
  controller-config: |-
    {
        "log-level": "info",
        "apic-hosts": [
            "10.10.20.12"
        ],
        "apic-username": "kubesbx08",
        "apic-private-key-path": "/usr/local/etc/aci-cert/user.key",
        "aci-prefix": "kubesbx08",
        "aci-vmm-type": "Kubernetes",
        "aci-vmm-domain": "kubesbx08",
        "aci-vmm-controller": "kubesbx08",
        "aci-policy-tenant": "kubesbx08",
        "require-netpol-annot": false,
        "aci-service-phys-dom": "kubesbx08-pdom",
        "aci-service-encap": "vlan-919",
        "aci-service-monitor-interval": 15,
        "aci-vrf-tenant": "common",
        "aci-l3out": "sbx_shared_L3Out",
        "aci-ext-networks": [
            "any_ip"
        ],
        "aci-vrf": "sbx_shared",
        "default-endpoint-group": {
            "policy-space": "kubesbx08",
            "name": "kubernetes|kube-default"
        },
        "namespace-default-endpoint-group": {
            "kube-system": {
                "policy-space": "kubesbx08",
                "name": "kubernetes|kube-system"
            }
        },
        "service-ip-pool": [
            {
                "start": "172.20.8.194", 
                "end": "172.20.8.222"
            }
        ],
        "static-service-ip-pool": [
            {
                "start": "172.20.8.226", 
                "end": "172.20.8.254"
            }
        ],
        "pod-ip-pool": [
            {
                "start": "10.208.0.2", 
                "end": "10.208.255.254"
            }
        ],
        "node-service-ip-pool": [
            {
                "start": "192.168.108.2", 
                "end": "192.168.108.254"
            }
        ],
        "node-service-subnets": [
            "192.168.108.1/24"
        ]
    }
  host-agent-config: |-
    {
        "log-level": "info",
        "aci-vmm-type": "Kubernetes",
        "aci-vmm-domain": "kubesbx08",
        "aci-vmm-controller": "kubesbx08",
        "aci-vrf": "sbx_shared",
        "aci-vrf-tenant": "common",
        "service-vlan": 919,
        "encap-type": "vxlan",
        "aci-infra-vlan": 4093,
        "cni-netconfig": [
            {
                "routes": [
                    {
                        "gw": "10.208.0.1", 
                        "dst": "0.0.0.0/0"
                    }
                ], 
                "subnet": "10.208.0.0/16", 
                "gateway": "10.208.0.1"
            }
        ]
    }
  opflex-agent-config: |-
    {
        "log": {
            "level": "info"
        },
        "opflex": {
        }
    }
---
apiVersion: v1
kind: Secret
metadata:
  name: aci-user-cert
  namespace: kube-system
  labels:
    aci-containers-config-version: "a7d695b6-5fd3-4ad5-a0ac-aeb052561ff3"
data:
  user.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUNkUUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQWw4d2dnSmJBZ0VBQW9HQkFNempwUHM0R01nL1dwVGUKUHFXMVc4eDNqd2dqR1BISENZTXYraWFRYzg1Um8zUUd1V0E3QUtOcUlGbFRVNWtHN1JXSWMwdGFWeHJ0NnNLawpNVnNtcFJObk0rYUYzY3g1R0pwMDdramEyaVVnSVkxeWZCUFREMVY2VzJMZ2lBcXZRek5GTkdrWWhFNnlwS3ptCm1hbzVhcW9XdzdsMkJKY0FGUGpMTHJva0hoMTlBZ01CQUFFQ2dZQVJPUTJVUklub3cxS1U4djJuSmxDYUptNnkKaTJpOFlqUE5nRW54MWZDMkppeXNReWh3QzJXcFZ2RnpNTXIxTVJ6YTA0YUZqZ21HYlB0djh5ZG05eCtuRkMwSgplZzBNNjQ1MnZOQjdNRStYRnNDU0VEM04ycCtONG1Nck1GR2FGRFh2N3ZSNzZyYmZkdEpYaWVUVkswbk5Kb0xsCitwTE9hL3doQmFhRDJBR2N6UUpCQVA1N3FmWkF2amFZWTZJbzFHaHcwcjRaMHpwNW5OMEwwZzB4em9EQTI1NnYKUzN4WFNMOUZIamlhN3RxN0ZQUGN0Umw1MUt3SmN6cEtmMno5UDZWSFdXc0NRUURPSEUwbGY5UHBsa1lCZ21ZOApxQlZhU1I1U21LWS9Pd1ZQcHVGOW53UUs5RWE2QlVncDUzNUgzQytEZ3MyV1JmU2Faa09FcUp3N0phV1NFeHhxCnloYTNBa0JXZExyc1QxaVFBYnV2cHNGcTdoR2F4ZmxPSDJ6Y2FCeW5vT2t3TXRVcUZ4SEZIMzQyaFF2Y1hUNlMKandaeVJ1UTcwSGtoTFdDNVIvLzhqaGttVkpRYkFrQVBoZ0lwZU44MUVLUmxLTFVhakc1UFJvS0tKZ1VmYmdxUQpYVGxPaE5PQkg3VFQvZUhaaGgzMHU1aTRodm1FLysvVVVTOTBwbDVkOWcvcVdKWWpWT1V4QWtBK09TME9xTmFwCnVESmF1NnRyZFdkcENUWkxyeklkQ09hUGRMejhUTGN0aEg5Nk5vVUd2K3ZqSnZKZ0dPZnkxclZZME8zSktVQVYKaStGSWYwcTkrRVZTCi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K
  user.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUI3RENDQVZVQ0FnUG9NQTBHQ1NxR1NJYjNEUUVCQlFVQU1ENHhDekFKQmdOVkJBWVRBbFZUTVJZd0ZBWUQKVlFRS0RBMURhWE5qYnlCVGVYTjBaVzF6TVJjd0ZRWURWUVFEREE1VmMyVnlJR3QxWW1WelluZ3dPREFlRncweApPREExTXpFeE5EUXlNVFphRncweU9EQTFNamt3TWpReU1UWmFNRDR4Q3pBSkJnTlZCQVlUQWxWVE1SWXdGQVlEClZRUUtEQTFEYVhOamJ5QlRlWE4wWlcxek1SY3dGUVlEVlFRRERBNVZjMlZ5SUd0MVltVnpZbmd3T0RDQm56QU4KQmdrcWhraUc5dzBCQVFFRkFBT0JqUUF3Z1lrQ2dZRUF6T09rK3pnWXlEOWFsTjQrcGJWYnpIZVBDQ01ZOGNjSgpneS82SnBCenpsR2pkQWE1WURzQW8yb2dXVk5UbVFidEZZaHpTMXBYR3UzcXdxUXhXeWFsRTJjejVvWGR6SGtZCm1uVHVTTnJhSlNBaGpYSjhFOU1QVlhwYll1Q0lDcTlETTBVMGFSaUVUcktrck9hWnFqbHFxaGJEdVhZRWx3QVUKK01zdXVpUWVIWDBDQXdFQUFUQU5CZ2txaGtpRzl3MEJBUVVGQUFPQmdRQ1JFS1YzREtJWGE0KzhROVZGY0ZXcApFaEdNSFBacjYvTzB6K1l1eUswc3pTeTl1Ui91Q1QwUlgxT20wOU5WZUpPNUxxbW83NHhjYUFBUnZUN2U0NmdOCmFaNWZ6VTJxL2RlSmpIWDVla2tTanFGK25NS294ejNyUmdUSjRrcmpoRTJaWkkzUXozZmg3WS9hc2o2WEx6YkoKVy82VGcyZXp6WjgyOWJoNU53MFNNZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aci-containers-controller
  namespace: kube-system
  labels:
    aci-containers-config-version: "a7d695b6-5fd3-4ad5-a0ac-aeb052561ff3"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aci-containers-host-agent
  namespace: kube-system
  labels:
    aci-containers-config-version: "a7d695b6-5fd3-4ad5-a0ac-aeb052561ff3"
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:
    aci-containers-config-version: "a7d695b6-5fd3-4ad5-a0ac-aeb052561ff3"
    network-plugin: aci-containers
  name: aci-containers:controller
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - namespaces
  - pods
  - endpoints
  - services
  verbs:
  - list
  - watch
  - get
- apiGroups:
  - "networking.k8s.io"
  resources:
  - networkpolicies
  verbs:
  - list
  - watch
  - get
- apiGroups:
  - "extensions"
  resources:
  - deployments
  - replicasets
  verbs:
  - list
  - watch
  - get
- apiGroups:
  - ""
  resources:
  - pods
  - nodes
  - services/status
  verbs:
  - update
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:
    aci-containers-config-version: "a7d695b6-5fd3-4ad5-a0ac-aeb052561ff3"
    network-plugin: aci-containers
  name: aci-containers:host-agent
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - pods
  - endpoints
  - services
  verbs:
  - list
  - watch
  - get
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: aci-containers:controller
  labels:
    aci-containers-config-version: "a7d695b6-5fd3-4ad5-a0ac-aeb052561ff3"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: aci-containers:controller
subjects:
- kind: ServiceAccount
  name: aci-containers-controller
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: aci-containers:host-agent
  labels:
    aci-containers-config-version: "a7d695b6-5fd3-4ad5-a0ac-aeb052561ff3"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: aci-containers:host-agent
subjects:
- kind: ServiceAccount
  name: aci-containers-host-agent
  namespace: kube-system
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: aci-containers-host
  namespace: kube-system
  labels:
    aci-containers-config-version: "a7d695b6-5fd3-4ad5-a0ac-aeb052561ff3"
    network-plugin: aci-containers
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      name: aci-containers-host
      network-plugin: aci-containers
  template:
    metadata:
      labels:
        name: aci-containers-host
        network-plugin: aci-containers
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      hostNetwork: true
      hostPID: true
      hostIPC: true
      serviceAccountName: aci-containers-host-agent
      tolerations:
        - key: CriticalAddonsOnly
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
      containers:
        - name: aci-containers-host
          image: noiro/aci-containers-host:1.7r86
          imagePullPolicy: Always
          securityContext:
            capabilities:
              add:
                - SYS_ADMIN
                - NET_ADMIN
          env:
            - name: KUBERNETES_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: cni-bin
              mountPath: /mnt/cni-bin
            - name: cni-conf
              mountPath: /mnt/cni-conf
            - name: hostvar
              mountPath: /usr/local/var
            - name: hostrun
              mountPath: /run
            - name: hostrun
              mountPath: /usr/local/run
            - name: opflex-hostconfig-volume
              mountPath: /usr/local/etc/opflex-agent-ovs/base-conf.d
            - name: host-config-volume
              mountPath: /usr/local/etc/aci-containers/
          livenessProbe:
            httpGet:
              path: /status
              port: 8090
        - name: opflex-agent
          image: noiro/opflex:1.7r70
          imagePullPolicy: Always
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          volumeMounts:
            - name: hostvar
              mountPath: /usr/local/var
            - name: hostrun
              mountPath: /run
            - name: hostrun
              mountPath: /usr/local/run
            - name: opflex-hostconfig-volume
              mountPath: /usr/local/etc/opflex-agent-ovs/base-conf.d
            - name: opflex-config-volume
              mountPath: /usr/local/etc/opflex-agent-ovs/conf.d
        - name: mcast-daemon
          image: noiro/opflex:1.7r70
          command: ["/bin/sh"]
          args: ["/usr/local/bin/launch-mcastdaemon.sh"]
          imagePullPolicy: Always
          volumeMounts:
            - name: hostvar
              mountPath: /usr/local/var
            - name: hostrun
              mountPath: /run
            - name: hostrun
              mountPath: /usr/local/run
      restartPolicy: Always
      volumes:
        - name: cni-bin
          hostPath:
            path: /opt
        - name: cni-conf
          hostPath:
            path: /etc
        - name: hostvar
          hostPath:
            path: /var
        - name: hostrun
          hostPath:
            path: /run
        - name: host-config-volume
          configMap:
            name: aci-containers-config
            items:
              - key: host-agent-config
                path: host-agent.conf
        - name: opflex-hostconfig-volume
          emptyDir:
            medium: Memory
        - name: opflex-config-volume
          configMap:
            name: aci-containers-config
            items:
              - key: opflex-agent-config
                path: local.conf
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: aci-containers-openvswitch
  namespace: kube-system
  labels:
    aci-containers-config-version: "a7d695b6-5fd3-4ad5-a0ac-aeb052561ff3"
    network-plugin: aci-containers
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      name: aci-containers-openvswitch
      network-plugin: aci-containers
  template:
    metadata:
      labels:
        name: aci-containers-openvswitch
        network-plugin: aci-containers
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      hostNetwork: true
      hostPID: true
      hostIPC: true
      serviceAccountName: aci-containers-host-agent
      tolerations:
        - key: CriticalAddonsOnly
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
      containers:
        - name: aci-containers-openvswitch
          image: noiro/openvswitch:1.7r24
          imagePullPolicy: Always
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - SYS_MODULE
                - SYS_NICE
                - IPC_LOCK
          env:
            - name: OVS_RUNDIR
              value: /usr/local/var/run/openvswitch
          volumeMounts:
            - name: hostvar
              mountPath: /usr/local/var
            - name: hostrun
              mountPath: /run
            - name: hostrun
              mountPath: /usr/local/run
            - name: hostetc
              mountPath: /usr/local/etc
            - name: hostmodules
              mountPath: /lib/modules
          livenessProbe:
            exec:
              command:
                - /usr/local/bin/liveness-ovs.sh
      restartPolicy: Always
      volumes:
        - name: hostetc
          hostPath:
            path: /etc
        - name: hostvar
          hostPath:
            path: /var
        - name: hostrun
          hostPath:
            path: /run
        - name: hostmodules
          hostPath:
            path: /lib/modules
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: aci-containers-controller
  namespace: kube-system
  labels:
    aci-containers-config-version: "a7d695b6-5fd3-4ad5-a0ac-aeb052561ff3"
    network-plugin: aci-containers
    name: aci-containers-controller
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      name: aci-containers-controller
      network-plugin: aci-containers
  template:
    metadata:
      name: aci-containers-controller
      namespace: kube-system
      labels:
        name: aci-containers-controller
        network-plugin: aci-containers
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      hostNetwork: true
      serviceAccountName: aci-containers-controller
      tolerations:
        - key: CriticalAddonsOnly
      containers:
        - name: aci-containers-controller
          image: noiro/aci-containers-controller:1.7r86
          imagePullPolicy: Always
          volumeMounts:
            - name: controller-config-volume
              mountPath: /usr/local/etc/aci-containers/
            - name: aci-user-cert-volume
              mountPath: /usr/local/etc/aci-cert/
          livenessProbe:
            httpGet:
              path: /status
              port: 8091
      volumes:
        - name: aci-user-cert-volume
          secret:
            secretName: aci-user-cert
        - name: controller-config-volume
          configMap:
            name: aci-containers-config
            items:
              - key: controller-config
                path: controller.conf
