---
- name: Remove previous docker installation
  become: yes
  yum:
    name: "{{ item.package }}"
    state: absent
  with_items: "{{ docker_cleanup_packages_EL }}"

- name: Import Docker CE repository gpg key
  become: yes
  rpm_key:
    key: https://download.docker.com/linux/centos/gpg
    state: present

- name: Add Docker CE repository
  become: yes
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo
    force: yes
    owner: root
    group: root
    mode: 0644

- name: Install Docker CE
  become: yes
  yum:
    name: docker-ce-17.12.1.ce-1.el7.centos
    state: present
    update_cache: yes

- name: Start docker
  become: yes
  service:
    name: docker
    state: started
    enabled: yes

- name: Check Docker compose bin file presence
  stat: path=/usr/local/bin/docker-compose
  register: dockercompose

- name: Install docker compose
  become: yes
  shell: curl -L https://github.com/docker/compose/releases/download/1.18.0/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
  when: dockercompose.stat.exists == false

- name: Apply executable permission
  become: yes
  file: path=/usr/local/bin/docker-compose mode="u+x,g+x,a+x"

- name: Test docker-compose version
  shell: docker-compose --version
  ignore_errors: true
