apiVersion: v1
kind: ConfigMap
metadata:
  name: aci-containers-config
  namespace: kube-system
  labels:
    aci-containers-config-version: "10632141-a176-4d8d-8ee1-59d111ba0194"
    network-plugin: aci-containers
data:
  controller-config: |-
    {
        "log-level": "info",
        "apic-hosts": [
            "10.10.20.12"
        ],
        "apic-username": "kubesbx20",
        "apic-private-key-path": "/usr/local/etc/aci-cert/user.key",
        "aci-prefix": "kubesbx20",
        "aci-vmm-type": "Kubernetes",
        "aci-vmm-domain": "kubesbx20",
        "aci-vmm-controller": "kubesbx20",
        "aci-policy-tenant": "kubesbx20",
        "require-netpol-annot": false,
        "aci-service-phys-dom": "kubesbx20-pdom",
        "aci-service-encap": "vlan-943",
        "aci-service-monitor-interval": 15,
        "aci-vrf-tenant": "common",
        "aci-l3out": "sbx_shared_L3Out",
        "aci-ext-networks": [
            "any_ip"
        ],
        "aci-vrf": "sbx_shared",
        "default-endpoint-group": {
            "policy-space": "kubesbx20",
            "name": "kubernetes|kube-default"
        },
        "namespace-default-endpoint-group": {
            "kube-system": {
                "policy-space": "kubesbx20",
                "name": "kubernetes|kube-system"
            }
        },
        "service-ip-pool": [
            {
                "start": "172.20.20.194", 
                "end": "172.20.20.222"
            }
        ],
        "static-service-ip-pool": [
            {
                "start": "172.20.20.226", 
                "end": "172.20.20.254"
            }
        ],
        "pod-ip-pool": [
            {
                "start": "10.220.0.2", 
                "end": "10.220.255.254"
            }
        ],
        "node-service-ip-pool": [
            {
                "start": "192.168.120.2", 
                "end": "192.168.120.254"
            }
        ],
        "node-service-subnets": [
            "192.168.120.1/24"
        ]
    }
  host-agent-config: |-
    {
        "log-level": "info",
        "aci-vmm-type": "Kubernetes",
        "aci-vmm-domain": "kubesbx20",
        "aci-vmm-controller": "kubesbx20",
        "aci-vrf": "sbx_shared",
        "aci-vrf-tenant": "common",
        "service-vlan": 943,
        "encap-type": "vxlan",
        "aci-infra-vlan": 4093,
        "cni-netconfig": [
            {
                "routes": [
                    {
                        "gw": "10.220.0.1", 
                        "dst": "0.0.0.0/0"
                    }
                ], 
                "subnet": "10.220.0.0/16", 
                "gateway": "10.220.0.1"
            }
        ]
    }
  opflex-agent-config: |-
    {
        "log": {
            "level": "info"
        },
        "opflex": {
        }
    }
---
apiVersion: v1
kind: Secret
metadata:
  name: aci-user-cert
  namespace: kube-system
  labels:
    aci-containers-config-version: "10632141-a176-4d8d-8ee1-59d111ba0194"
data:
  user.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUNkd0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQW1Fd2dnSmRBZ0VBQW9HQkFNWm8yOG45bkxzRHFZdzAKa2ZTUmVZQXIrWE9jK2o3VmFBN3A2ZWRYaDEvRDFPUkZJUWdQU0xFZUp1LzF0NGpyRkMzV2FiaGIvMTdZZmc4SQp1S2QvcDFlTU9sYUx6MFQzSFBDMGpmbDZPWVlqLzhlSFg4ejdPalhiaWNYUWtUbnVlMjNGZ2N5STUwSStOK2ZMCmIvVUd5bW10TG1KWU5OdnpkOGMyRUJmQTRtTFRBZ01CQUFFQ2dZQkdQSmlSeU5YUzNsa0c2UlZDSHIyRVFnenMKZ0lXVitMWDlrWkRiOUlCWHhsdDI4NEhkK0lzaktDbGdpUHVQM0tnb0VkOGJCSFpDZlNFaThWTnMrQ09rbWFiLwoxY2RuTUx4QWtDTmZQK21iSktLRDcwd3FJNEJHKy9qNDI4YTN1ZkRoTGNjQS9JcVlUSmpzbXJ6V2hNZWplVXRZCkt1NlZPeWdhMytPNEtXcG9BUUpCQVA0c1lhVXd6U2pyUW53R1ZrcGlLUzBwWkJCNDVwUjdWaDBVTXhRNjNnK08KQjN1NHVJVU91dnI2aVZUTTUzSXNSYWhQZGRkOVhSaXNiK2hXWko0TVFDRUNRUURIMWVLVE5PeHFsTFkwbWk2ZwpZaS8yZ3B2RHMydFpOblhhdFVGSy91MVhtQUNiOStER29aRS9LbUJkZGw4aExGbXVNbXFyQThPYU5LMEZBR2g4CmZ4UnpBa0VBc3FxWDZQcW8vSDZET1pOcXpOYTdneGQ1VTJycENxNjRGYkRCUnhNcVRWelZQYzdYUmhEWXR0dXQKOVlJam4wb25uT3hlTlovVjlTWWhjL3htdGdKK2dRSkFWWFF3SEpVQUdCK1p2dXJEejQvTlJOUGJPaGVxYXc3dgozT092bFJ0b2NSR3VDUVE1MlpiVG5yaEhWeEE4WTlvc1MyS0IzTG1TVm9uNkJ1NkN2K0l6NHdKQkFJOEtuYVg3CjRSUldpU2swMnlDM3pEd1gwTU1LRzYwR2lvUnFSQ3FJWVpoaGNTVXMvZmhpb0FjTkxPcklyZ2xkSGgyczZLdnEKZkt6WnYxMGZvY1dWdzAwPQotLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tCg==
  user.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUI3RENDQVZVQ0FnUG9NQTBHQ1NxR1NJYjNEUUVCQlFVQU1ENHhDekFKQmdOVkJBWVRBbFZUTVJZd0ZBWUQKVlFRS0RBMURhWE5qYnlCVGVYTjBaVzF6TVJjd0ZRWURWUVFEREE1VmMyVnlJR3QxWW1WelluZ3lNREFlRncweApPREE0TURrd05UVXpNamhhRncweU9EQTRNRFl4TnpVek1qaGFNRDR4Q3pBSkJnTlZCQVlUQWxWVE1SWXdGQVlEClZRUUtEQTFEYVhOamJ5QlRlWE4wWlcxek1SY3dGUVlEVlFRRERBNVZjMlZ5SUd0MVltVnpZbmd5TURDQm56QU4KQmdrcWhraUc5dzBCQVFFRkFBT0JqUUF3Z1lrQ2dZRUF4bWpieWYyY3V3T3BqRFNSOUpGNWdDdjVjNXo2UHRWbwpEdW5wNTFlSFg4UFU1RVVoQ0E5SXNSNG03L1czaU9zVUxkWnB1RnYvWHRoK0R3aTRwMytuVjR3NlZvdlBSUGNjCjhMU04rWG81aGlQL3g0ZGZ6UHM2TmR1SnhkQ1JPZTU3YmNXQnpJam5RajQzNTh0djlRYkthYTB1WWxnMDIvTjMKeHpZUUY4RGlZdE1DQXdFQUFUQU5CZ2txaGtpRzl3MEJBUVVGQUFPQmdRQUprd3JMM0gvRitBOUR4b2FPeDRiUwprUVY3aVI3bWQwZlBXaFB1T2poVFFMaU9UYmtxaER1V1pRUlhSQkxOUVgvMlJiUjErbVpsQmdIeDh5ZXpLS3l4CkVFUmgzdVVHYTQxYWJHU2hxc0RweTEvckIzU2pOdWxpdDc4S0hqZmpxbjM0aVN6eFZ3NGJWclRrVTI1aitYTWMKTDhJM0NyU1FlWDFVVWtTWkV2MXhQQT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aci-containers-controller
  namespace: kube-system
  labels:
    aci-containers-config-version: "10632141-a176-4d8d-8ee1-59d111ba0194"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aci-containers-host-agent
  namespace: kube-system
  labels:
    aci-containers-config-version: "10632141-a176-4d8d-8ee1-59d111ba0194"
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:
    aci-containers-config-version: "10632141-a176-4d8d-8ee1-59d111ba0194"
    network-plugin: aci-containers
  name: aci-containers:controller
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - namespaces
  - pods
  - endpoints
  - services
  verbs:
  - list
  - watch
  - get
- apiGroups:
  - "networking.k8s.io"
  resources:
  - networkpolicies
  verbs:
  - list
  - watch
  - get
- apiGroups:
  - "extensions"
  resources:
  - deployments
  - replicasets
  verbs:
  - list
  - watch
  - get
- apiGroups:
  - ""
  resources:
  - pods
  - nodes
  - services/status
  verbs:
  - update
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:
    aci-containers-config-version: "10632141-a176-4d8d-8ee1-59d111ba0194"
    network-plugin: aci-containers
  name: aci-containers:host-agent
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - pods
  - endpoints
  - services
  verbs:
  - list
  - watch
  - get
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: aci-containers:controller
  labels:
    aci-containers-config-version: "10632141-a176-4d8d-8ee1-59d111ba0194"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: aci-containers:controller
subjects:
- kind: ServiceAccount
  name: aci-containers-controller
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: aci-containers:host-agent
  labels:
    aci-containers-config-version: "10632141-a176-4d8d-8ee1-59d111ba0194"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: aci-containers:host-agent
subjects:
- kind: ServiceAccount
  name: aci-containers-host-agent
  namespace: kube-system
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: aci-containers-host
  namespace: kube-system
  labels:
    aci-containers-config-version: "10632141-a176-4d8d-8ee1-59d111ba0194"
    network-plugin: aci-containers
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      name: aci-containers-host
      network-plugin: aci-containers
  template:
    metadata:
      labels:
        name: aci-containers-host
        network-plugin: aci-containers
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      hostNetwork: true
      hostPID: true
      hostIPC: true
      serviceAccountName: aci-containers-host-agent
      tolerations:
        - key: CriticalAddonsOnly
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
      containers:
        - name: aci-containers-host
          image: noiro/aci-containers-host:1.7r86
          imagePullPolicy: Always
          securityContext:
            capabilities:
              add:
                - SYS_ADMIN
                - NET_ADMIN
          env:
            - name: KUBERNETES_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: cni-bin
              mountPath: /mnt/cni-bin
            - name: cni-conf
              mountPath: /mnt/cni-conf
            - name: hostvar
              mountPath: /usr/local/var
            - name: hostrun
              mountPath: /run
            - name: hostrun
              mountPath: /usr/local/run
            - name: opflex-hostconfig-volume
              mountPath: /usr/local/etc/opflex-agent-ovs/base-conf.d
            - name: host-config-volume
              mountPath: /usr/local/etc/aci-containers/
          livenessProbe:
            httpGet:
              path: /status
              port: 8090
        - name: opflex-agent
          image: noiro/opflex:1.7r70
          imagePullPolicy: Always
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          volumeMounts:
            - name: hostvar
              mountPath: /usr/local/var
            - name: hostrun
              mountPath: /run
            - name: hostrun
              mountPath: /usr/local/run
            - name: opflex-hostconfig-volume
              mountPath: /usr/local/etc/opflex-agent-ovs/base-conf.d
            - name: opflex-config-volume
              mountPath: /usr/local/etc/opflex-agent-ovs/conf.d
        - name: mcast-daemon
          image: noiro/opflex:1.7r70
          command: ["/bin/sh"]
          args: ["/usr/local/bin/launch-mcastdaemon.sh"]
          imagePullPolicy: Always
          volumeMounts:
            - name: hostvar
              mountPath: /usr/local/var
            - name: hostrun
              mountPath: /run
            - name: hostrun
              mountPath: /usr/local/run
      restartPolicy: Always
      volumes:
        - name: cni-bin
          hostPath:
            path: /opt
        - name: cni-conf
          hostPath:
            path: /etc
        - name: hostvar
          hostPath:
            path: /var
        - name: hostrun
          hostPath:
            path: /run
        - name: host-config-volume
          configMap:
            name: aci-containers-config
            items:
              - key: host-agent-config
                path: host-agent.conf
        - name: opflex-hostconfig-volume
          emptyDir:
            medium: Memory
        - name: opflex-config-volume
          configMap:
            name: aci-containers-config
            items:
              - key: opflex-agent-config
                path: local.conf
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: aci-containers-openvswitch
  namespace: kube-system
  labels:
    aci-containers-config-version: "10632141-a176-4d8d-8ee1-59d111ba0194"
    network-plugin: aci-containers
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      name: aci-containers-openvswitch
      network-plugin: aci-containers
  template:
    metadata:
      labels:
        name: aci-containers-openvswitch
        network-plugin: aci-containers
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      hostNetwork: true
      hostPID: true
      hostIPC: true
      serviceAccountName: aci-containers-host-agent
      tolerations:
        - key: CriticalAddonsOnly
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
      containers:
        - name: aci-containers-openvswitch
          image: noiro/openvswitch:1.7r24
          imagePullPolicy: Always
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - SYS_MODULE
                - SYS_NICE
                - IPC_LOCK
          env:
            - name: OVS_RUNDIR
              value: /usr/local/var/run/openvswitch
          volumeMounts:
            - name: hostvar
              mountPath: /usr/local/var
            - name: hostrun
              mountPath: /run
            - name: hostrun
              mountPath: /usr/local/run
            - name: hostetc
              mountPath: /usr/local/etc
            - name: hostmodules
              mountPath: /lib/modules
          livenessProbe:
            exec:
              command:
                - /usr/local/bin/liveness-ovs.sh
      restartPolicy: Always
      volumes:
        - name: hostetc
          hostPath:
            path: /etc
        - name: hostvar
          hostPath:
            path: /var
        - name: hostrun
          hostPath:
            path: /run
        - name: hostmodules
          hostPath:
            path: /lib/modules
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: aci-containers-controller
  namespace: kube-system
  labels:
    aci-containers-config-version: "10632141-a176-4d8d-8ee1-59d111ba0194"
    network-plugin: aci-containers
    name: aci-containers-controller
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      name: aci-containers-controller
      network-plugin: aci-containers
  template:
    metadata:
      name: aci-containers-controller
      namespace: kube-system
      labels:
        name: aci-containers-controller
        network-plugin: aci-containers
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      hostNetwork: true
      serviceAccountName: aci-containers-controller
      tolerations:
        - key: CriticalAddonsOnly
      containers:
        - name: aci-containers-controller
          image: noiro/aci-containers-controller:1.7r86
          imagePullPolicy: Always
          volumeMounts:
            - name: controller-config-volume
              mountPath: /usr/local/etc/aci-containers/
            - name: aci-user-cert-volume
              mountPath: /usr/local/etc/aci-cert/
          livenessProbe:
            httpGet:
              path: /status
              port: 8091
      volumes:
        - name: aci-user-cert-volume
          secret:
            secretName: aci-user-cert
        - name: controller-config-volume
          configMap:
            name: aci-containers-config
            items:
              - key: controller-config
                path: controller.conf
