apiVersion: v1
kind: ServiceAccount
metadata:
   name: myaccount
   namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
   name: pod-reader
   namespace: default
rules:
   - apiGroups: [""]
     resources: ["pods"]
     verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
   name: pod-reader-rolebinding
   namespace: default
subjects:
   - kind: ServiceAccount
     name: myaccount
     apiGroup: ""
roleRef:
   kind: Role
   name: pod-reader
   apiGroup: rbac.authorization.k8s.io

