apiVersion: v1
kind: ConfigMap
metadata:
  name: aci-containers-config
  namespace: kube-system
  labels:
    aci-containers-config-version: "28708283-f3dd-44d1-a55e-7893dedf5998"
    network-plugin: aci-containers
data:
  controller-config: |-
    {
        "log-level": "info",
        "apic-hosts": [
            "10.10.20.12"
        ],
        "apic-username": "kubesbx38",
        "apic-private-key-path": "/usr/local/etc/aci-cert/user.key",
        "aci-prefix": "kubesbx38",
        "aci-vmm-type": "Kubernetes",
        "aci-vmm-domain": "kubesbx38",
        "aci-vmm-controller": "kubesbx38",
        "aci-policy-tenant": "kubesbx38",
        "require-netpol-annot": false,
        "aci-service-phys-dom": "kubesbx38-pdom",
        "aci-service-encap": "vlan-979",
        "aci-service-monitor-interval": 15,
        "aci-vrf-tenant": "common",
        "aci-l3out": "sbx_shared_L3Out",
        "aci-ext-networks": [
            "any_ip"
        ],
        "aci-vrf": "sbx_shared",
        "default-endpoint-group": {
            "policy-space": "kubesbx38",
            "name": "kubernetes|kube-default"
        },
        "namespace-default-endpoint-group": {
            "kube-system": {
                "policy-space": "kubesbx38",
                "name": "kubernetes|kube-system"
            }
        },
        "service-ip-pool": [
            {
                "start": "172.20.38.194", 
                "end": "172.20.38.222"
            }
        ],
        "static-service-ip-pool": [
            {
                "start": "172.20.38.226", 
                "end": "172.20.38.254"
            }
        ],
        "pod-ip-pool": [
            {
                "start": "10.238.0.2", 
                "end": "10.238.255.254"
            }
        ],
        "node-service-ip-pool": [
            {
                "start": "192.168.138.2", 
                "end": "192.168.138.254"
            }
        ],
        "node-service-subnets": [
            "192.168.138.1/24"
        ]
    }
  host-agent-config: |-
    {
        "log-level": "info",
        "aci-vmm-type": "Kubernetes",
        "aci-vmm-domain": "kubesbx38",
        "aci-vmm-controller": "kubesbx38",
        "aci-vrf": "sbx_shared",
        "aci-vrf-tenant": "common",
        "service-vlan": 979,
        "encap-type": "vxlan",
        "aci-infra-vlan": 4093,
        "cni-netconfig": [
            {
                "routes": [
                    {
                        "gw": "10.238.0.1", 
                        "dst": "0.0.0.0/0"
                    }
                ], 
                "subnet": "10.238.0.0/16", 
                "gateway": "10.238.0.1"
            }
        ]
    }
  opflex-agent-config: |-
    {
        "log": {
            "level": "info"
        },
        "opflex": {
        }
    }
---
apiVersion: v1
kind: Secret
metadata:
  name: aci-user-cert
  namespace: kube-system
  labels:
    aci-containers-config-version: "28708283-f3dd-44d1-a55e-7893dedf5998"
data:
  user.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUNlQUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQW1Jd2dnSmVBZ0VBQW9HQkFNQ01Kc3l1LzNXclNQRjYKZHJHcDN6OTJGL2NucFZxVHg3RG54RkxPQUJLZGZVR3lOQUgyQ3hhYXo0c2VBa2IvUnFzYlMwQVJpZkY0QWU5SQpwOTJERXNENW5GM3JUTkZ1bjAyeERwYzVPUEpFZnNMZEtZQ3JoQXpyL0dZOERXenFLVjFNTnhHVHBtRGJNalBTClRhTDBZZ2Uvb2xkTEUzWE93QjRhTERRZ3g4RDlBZ01CQUFFQ2dZRUFqblVqSDcwNTlHMU9BcHVBeGVIUThyc0UKOEMrOC8wN25KOVBTUlJGMHJGRXBJem9ka0hYaHJrL0x6am5kcFhtcFoxOUNSWnkwV3B0WGt4cEdXSFZwb1dMdwoyYThvaSsraHJVTmNqV05RaUlicHgzYTkwcWtTSEVMa0hpS2MyT1ZHSUJ2eDZqNzRxWjZnNDRFc1UwQXhJUjRTCkdVK3FNMlg4VlFiNldIdUVZQUVDUVFEMDRYa285UDVDZGEvS0JzZEpGWmFSZW9ZOTZoOFNzeGowZHJGaWxHMnUKQ1lZYTdEbVBPanhOTUJNRDVMejRUVzRUK2hIb2VQSHZCOXJEOVhuallNa0JBa0VBeVVwWllFeHlYU0RPUE00SApHY0MyeEFhbkpFUmJtdWNrUW9pZGlvN0YzWTl4K3l6OTIyL2JSdDRXcUpEcWV2QWtnalNnOGp2ak05REpkdjVDClZ1NGIvUUpCQU9MMno5czhKeVRsK3dZZWZqcW92YU1ja3F0MEFWVE5sa1dPZFI1UFA5RGNsdVVCS09BdE01Sy8KQ2dERDBybTQybHU5blRlQVVZd2dGWTBtU2RDSzlnRUNRSG1hV1BROE9ycllIci9ORjYwUEoxcTFTalEydDhDVQo4dXJlN1kzUFF1bmV4dFVmRVIySUxjaGFVd1h5eGpVTzduOWFuQUM2L1Q5SVd1MXdIVk8yOVdFQ1FRQ2tEdk1ECjRITGNqdnlrRXRVMDI1UlVCdVF3d29UOGVLWEVtZk9IRUJ4Q21VaG5Hckl5Wi95UGlRQmlIR0gwUXlLblJUaFEKUTFWL2lmM0pHcUIzM2QvRAotLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tCg==
  user.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUI3RENDQVZVQ0FnUG9NQTBHQ1NxR1NJYjNEUUVCQlFVQU1ENHhDekFKQmdOVkJBWVRBbFZUTVJZd0ZBWUQKVlFRS0RBMURhWE5qYnlCVGVYTjBaVzF6TVJjd0ZRWURWUVFEREE1VmMyVnlJR3QxWW1WelluZ3pPREFlRncweApPREE0TURrd05UVTFNalphRncweU9EQTRNRFl4TnpVMU1qWmFNRDR4Q3pBSkJnTlZCQVlUQWxWVE1SWXdGQVlEClZRUUtEQTFEYVhOamJ5QlRlWE4wWlcxek1SY3dGUVlEVlFRRERBNVZjMlZ5SUd0MVltVnpZbmd6T0RDQm56QU4KQmdrcWhraUc5dzBCQVFFRkFBT0JqUUF3Z1lrQ2dZRUF3SXdteks3L2RhdEk4WHAyc2FuZlAzWVg5eWVsV3BQSApzT2ZFVXM0QUVwMTlRYkkwQWZZTEZwclBpeDRDUnY5R3F4dExRQkdKOFhnQjcwaW4zWU1Td1BtY1hldE0wVzZmClRiRU9sems0OGtSK3d0MHBnS3VFRE92OFpqd05iT29wWFV3M0VaT21ZTnN5TTlKTm92UmlCNytpVjBzVGRjN0EKSGhvc05DREh3UDBDQXdFQUFUQU5CZ2txaGtpRzl3MEJBUVVGQUFPQmdRQzR5R2pLSlNRK2UwSW1FRFU0UGtPZApBbWJFanQyOVNKMUFadzU4aGxlSFR1OVBsV2Nldkl5MXZ4ZjlaMHQ5Z3BLWW42aDdQWkpUOWc4d25IMEs1WUIvCmtSaTR6YjY0YkRnT1gyRnJ5OGVadndTQ042L016UE9zdHJvMHZCTHFOOXVsRndXd1BYbU5JK05CMEg3dmdsSUsKOXBWbmZRcjh1OTZjbmNDTnNTUmJ0UT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aci-containers-controller
  namespace: kube-system
  labels:
    aci-containers-config-version: "28708283-f3dd-44d1-a55e-7893dedf5998"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aci-containers-host-agent
  namespace: kube-system
  labels:
    aci-containers-config-version: "28708283-f3dd-44d1-a55e-7893dedf5998"
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:
    aci-containers-config-version: "28708283-f3dd-44d1-a55e-7893dedf5998"
    network-plugin: aci-containers
  name: aci-containers:controller
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - namespaces
  - pods
  - endpoints
  - services
  verbs:
  - list
  - watch
  - get
- apiGroups:
  - "networking.k8s.io"
  resources:
  - networkpolicies
  verbs:
  - list
  - watch
  - get
- apiGroups:
  - "extensions"
  resources:
  - deployments
  - replicasets
  verbs:
  - list
  - watch
  - get
- apiGroups:
  - ""
  resources:
  - pods
  - nodes
  - services/status
  verbs:
  - update
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:
    aci-containers-config-version: "28708283-f3dd-44d1-a55e-7893dedf5998"
    network-plugin: aci-containers
  name: aci-containers:host-agent
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - pods
  - endpoints
  - services
  verbs:
  - list
  - watch
  - get
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: aci-containers:controller
  labels:
    aci-containers-config-version: "28708283-f3dd-44d1-a55e-7893dedf5998"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: aci-containers:controller
subjects:
- kind: ServiceAccount
  name: aci-containers-controller
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: aci-containers:host-agent
  labels:
    aci-containers-config-version: "28708283-f3dd-44d1-a55e-7893dedf5998"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: aci-containers:host-agent
subjects:
- kind: ServiceAccount
  name: aci-containers-host-agent
  namespace: kube-system
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: aci-containers-host
  namespace: kube-system
  labels:
    aci-containers-config-version: "28708283-f3dd-44d1-a55e-7893dedf5998"
    network-plugin: aci-containers
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      name: aci-containers-host
      network-plugin: aci-containers
  template:
    metadata:
      labels:
        name: aci-containers-host
        network-plugin: aci-containers
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      hostNetwork: true
      hostPID: true
      hostIPC: true
      serviceAccountName: aci-containers-host-agent
      tolerations:
        - key: CriticalAddonsOnly
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
      containers:
        - name: aci-containers-host
          image: noiro/aci-containers-host:1.7r86
          imagePullPolicy: Always
          securityContext:
            capabilities:
              add:
                - SYS_ADMIN
                - NET_ADMIN
          env:
            - name: KUBERNETES_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: cni-bin
              mountPath: /mnt/cni-bin
            - name: cni-conf
              mountPath: /mnt/cni-conf
            - name: hostvar
              mountPath: /usr/local/var
            - name: hostrun
              mountPath: /run
            - name: hostrun
              mountPath: /usr/local/run
            - name: opflex-hostconfig-volume
              mountPath: /usr/local/etc/opflex-agent-ovs/base-conf.d
            - name: host-config-volume
              mountPath: /usr/local/etc/aci-containers/
          livenessProbe:
            httpGet:
              path: /status
              port: 8090
        - name: opflex-agent
          image: noiro/opflex:1.7r70
          imagePullPolicy: Always
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          volumeMounts:
            - name: hostvar
              mountPath: /usr/local/var
            - name: hostrun
              mountPath: /run
            - name: hostrun
              mountPath: /usr/local/run
            - name: opflex-hostconfig-volume
              mountPath: /usr/local/etc/opflex-agent-ovs/base-conf.d
            - name: opflex-config-volume
              mountPath: /usr/local/etc/opflex-agent-ovs/conf.d
        - name: mcast-daemon
          image: noiro/opflex:1.7r70
          command: ["/bin/sh"]
          args: ["/usr/local/bin/launch-mcastdaemon.sh"]
          imagePullPolicy: Always
          volumeMounts:
            - name: hostvar
              mountPath: /usr/local/var
            - name: hostrun
              mountPath: /run
            - name: hostrun
              mountPath: /usr/local/run
      restartPolicy: Always
      volumes:
        - name: cni-bin
          hostPath:
            path: /opt
        - name: cni-conf
          hostPath:
            path: /etc
        - name: hostvar
          hostPath:
            path: /var
        - name: hostrun
          hostPath:
            path: /run
        - name: host-config-volume
          configMap:
            name: aci-containers-config
            items:
              - key: host-agent-config
                path: host-agent.conf
        - name: opflex-hostconfig-volume
          emptyDir:
            medium: Memory
        - name: opflex-config-volume
          configMap:
            name: aci-containers-config
            items:
              - key: opflex-agent-config
                path: local.conf
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: aci-containers-openvswitch
  namespace: kube-system
  labels:
    aci-containers-config-version: "28708283-f3dd-44d1-a55e-7893dedf5998"
    network-plugin: aci-containers
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      name: aci-containers-openvswitch
      network-plugin: aci-containers
  template:
    metadata:
      labels:
        name: aci-containers-openvswitch
        network-plugin: aci-containers
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      hostNetwork: true
      hostPID: true
      hostIPC: true
      serviceAccountName: aci-containers-host-agent
      tolerations:
        - key: CriticalAddonsOnly
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
      containers:
        - name: aci-containers-openvswitch
          image: noiro/openvswitch:1.7r24
          imagePullPolicy: Always
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - SYS_MODULE
                - SYS_NICE
                - IPC_LOCK
          env:
            - name: OVS_RUNDIR
              value: /usr/local/var/run/openvswitch
          volumeMounts:
            - name: hostvar
              mountPath: /usr/local/var
            - name: hostrun
              mountPath: /run
            - name: hostrun
              mountPath: /usr/local/run
            - name: hostetc
              mountPath: /usr/local/etc
            - name: hostmodules
              mountPath: /lib/modules
          livenessProbe:
            exec:
              command:
                - /usr/local/bin/liveness-ovs.sh
      restartPolicy: Always
      volumes:
        - name: hostetc
          hostPath:
            path: /etc
        - name: hostvar
          hostPath:
            path: /var
        - name: hostrun
          hostPath:
            path: /run
        - name: hostmodules
          hostPath:
            path: /lib/modules
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: aci-containers-controller
  namespace: kube-system
  labels:
    aci-containers-config-version: "28708283-f3dd-44d1-a55e-7893dedf5998"
    network-plugin: aci-containers
    name: aci-containers-controller
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      name: aci-containers-controller
      network-plugin: aci-containers
  template:
    metadata:
      name: aci-containers-controller
      namespace: kube-system
      labels:
        name: aci-containers-controller
        network-plugin: aci-containers
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      hostNetwork: true
      serviceAccountName: aci-containers-controller
      tolerations:
        - key: CriticalAddonsOnly
      containers:
        - name: aci-containers-controller
          image: noiro/aci-containers-controller:1.7r86
          imagePullPolicy: Always
          volumeMounts:
            - name: controller-config-volume
              mountPath: /usr/local/etc/aci-containers/
            - name: aci-user-cert-volume
              mountPath: /usr/local/etc/aci-cert/
          livenessProbe:
            httpGet:
              path: /status
              port: 8091
      volumes:
        - name: aci-user-cert-volume
          secret:
            secretName: aci-user-cert
        - name: controller-config-volume
          configMap:
            name: aci-containers-config
            items:
              - key: controller-config
                path: controller.conf
