---
# - name: Prep Nodes
#   hosts: kube
#   become: yes
#
#   tasks:
#     - name: Create Setup Directories
#       with_items:
#         - /home/developer/kubesetup
#         - /home/developer/kubesetup/network
#       file:
#         name: "{{ item }}"
#         state: directory
#         mode: 0755
#
- name: Configure Network Interface for K8s to ACI
  hosts: kube
  become: yes

  tasks:
    - name: Create Ethernet Configuration File
      template:
        src: templates/ifcfg-INT.j2
        # dest: /home/developer/kubesetup/network/ifcfg-{{ aci_interface }}
        dest: /etc/sysconfig/network-scripts/ifcfg-{{ aci_interface }}
        owner: root
        group: root
        mode: 0644

    - name: Create Node VLAN Interface
      template:
        src: templates/node-ifcfg.j2
        # dest: /home/developer/kubesetup/network/ifcfg-{{ aci_interface }}.{{ node.vlan }}
        dest: /etc/sysconfig/network-scripts/ifcfg-{{ aci_interface }}.{{ node.vlan }}
        owner: root
        group: root
        mode: 0644

    #     # Per the troubleshooting guide, this interface should NOT exist
    # - name: Create Service VLAN Interface
    #   template:
    #     src: templates/service-ifcfg.j2
    #     # dest: /home/developer/kubesetup/network/ifcfg-{{ aci_interface }}.{{ node.vlan }}
    #     dest: /etc/sysconfig/network-scripts/ifcfg-{{ aci_interface }}.{{ service.vlan }}
    #     owner: root
    #     group: root
    #     mode: 0644

    - name: Create Infra VLAN Interface
      template:
        src: templates/infra-ifcfg.j2
        # dest: /home/developer/kubesetup/network/ifcfg-{{ aci_interface }}.{{ node.vlan }}
        dest: /etc/sysconfig/network-scripts/ifcfg-{{ aci_interface }}.{{ infra.vlan }}
        owner: root
        group: root
        mode: 0644

    - name: Restart Network
      service:
        name: network
        state: restarted

    - name: Re-query facts for new interfaces
      setup:
        gather_subset: all

    - name: Create DHCP Client Configuration for Infra
      template:
        src: templates/infra_dhclient.j2
        dest: /etc/dhcp/dhclient-{{ aci_interface }}.{{ infra.vlan }}.conf
        owner: root
        group: root
        mode: 0644

    - name: Add Fabric Multicast Subnet Route
      template:
        src: templates/infra_route.j2
        dest: /etc/sysconfig/network-scripts/route-{{ aci_interface }}.{{ infra.vlan }}
        owner: root
        group: root
        mode: 0644

    - name: Remove Default Route from Mgmt Interface, pt1
      with_items:
        - "DEFROUTE=no"
        - "#GATEWAY=172.20.0.1"
      lineinfile:
        path: /etc/sysconfig/network-scripts/ifcfg-{{ mgmt.interface }}
        line: "{{ item }}"
        state: present

    - name: Remove Default Route from Mgmt Interface, pt2
      with_items:
        - "DEFROUTE=yes"
        - "GATEWAY=172.20.0.1"
      lineinfile:
        path: /etc/sysconfig/network-scripts/ifcfg-{{ mgmt.interface }}
        line: "{{ item }}"
        state: absent

    - name: Restart Network
      service:
        name: network
        state: restarted

# - name: Enable DHCP for infra Interface
#   hosts: kube
#   become: yes
#
#   tasks:
#     - name: Print Infra Mac
#       debug:
#         msg: Infra MAC {{ aci_interface }}.{{ infra.vlan }} - {{ hostvars[inventory_hostname]['ansible_{}.{}'.format(aci_interface, infra['vlan'])]['macaddress'] }}
#
#     - name: Create DHCP Client Configuration for Infra
#       template:
#         src: templates/infra_dhclient.j2
#         dest: /etc/dhcp/dhclient-{{ aci_interface }}.{{ infra.vlan }}.conf
#         owner: root
#         group: root
#         mode: 0644
