apiVersion: v1
kind: Pod
metadata:
   name: hello-cisco
   annotations:
      ping: pong
spec:
   containers:
   - name: hello-cisco
     image: mimaurer/hello-cisco:v1
     ports:
     - containerPort: 5000
